/* eslint-disable @typescript-eslint/no-unused-vars */
// src/data.ts

export interface Restaurant {
  id: string;
  name: string;
  category:
    | "한식"
    | "일식"
    | "중식"
    | "간편식·분식"
    | "고기"
    | "양식·아시안"
    | "주류"
    | "카페·디저트";
  type: "식사" | "술집" | "카페";
  zone: "정문" | "A" | "B" | "C";
  solo: boolean; // 혼밥 가능 여부 (true: 혼밥 가능, false: 혼밥 어려움)
}

export const restaurants: Restaurant[] = [
  // ───────────────────────────────────────────────
  // 한식 (K1 ~ K43)
  // ───────────────────────────────────────────────
  {
    id: "K1",
    name: "차부안식당",
    category: "한식",
    type: "식사",
    zone: "C",
    solo: false,
  },
  {
    id: "K2",
    name: "고집칡냉면",
    category: "한식",
    type: "식사",
    zone: "C",
    solo: false,
  },
  {
    id: "K3",
    name: "치즈밥있슈명지대점",
    category: "한식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "K4",
    name: "수인김치찜",
    category: "한식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "K6",
    name: "화화매운갈비찜",
    category: "한식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "K7",
    name: "쏘울푸드",
    category: "한식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "K8",
    name: "생선구이와 돈까스2",
    category: "한식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "K9",
    name: "한솔식당 명지대점",
    category: "한식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "K10",
    name: "투데이하우스",
    category: "한식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "K11",
    name: "대빈",
    category: "한식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "K12",
    name: "밥은화 명지대점",
    category: "한식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "K13",
    name: "보리향기 본점",
    category: "한식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "K14",
    name: "소반",
    category: "한식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "K15",
    name: "동궁찜닭 명지대점",
    category: "한식",
    type: "식사",
    zone: "A",
    solo: false,
  },
  {
    id: "K16",
    name: "엄마밥상",
    category: "한식",
    type: "식사",
    zone: "A",
    solo: true,
  },
  {
    id: "K17",
    name: "쿡스",
    category: "한식",
    type: "식사",
    zone: "A",
    solo: true,
  },
  {
    id: "K18",
    name: "민스키친",
    category: "한식",
    type: "식사",
    zone: "A",
    solo: false,
  },
  {
    id: "K19",
    name: "마닐로우",
    category: "한식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "K20",
    name: "베가 보쌈 명지대점",
    category: "한식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "K21",
    name: "청춘보쌈",
    category: "한식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "K22",
    name: "봉구네가마솥순대국",
    category: "한식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "K23",
    name: "호우동 명지점",
    category: "한식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "K24",
    name: "삼청식당",
    category: "한식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "K25",
    name: "돼지주막",
    category: "한식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "K26",
    name: "명지 밥집",
    category: "한식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "K27",
    name: "만득이네 두루치기",
    category: "한식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "K29",
    name: "킹콩부대찌개 명지대점",
    category: "한식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "K30",
    name: "군산식당",
    category: "한식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "K31",
    name: "고인돌식당",
    category: "한식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "K32",
    name: "일로칡냉면 명지대점",
    category: "한식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "K33",
    name: "밀이삭칼국수",
    category: "한식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "K34",
    name: "미식가",
    category: "한식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "K35",
    name: "백련팥죽",
    category: "한식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "K36",
    name: "통큰한식부페",
    category: "한식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "K37",
    name: "기쁨이네",
    category: "한식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "K38",
    name: "기린식당",
    category: "한식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "K40",
    name: "정가네맛집",
    category: "한식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "K41",
    name: "본죽&비빔밥 남가좌점",
    category: "한식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "K42",
    name: "대가감자탕뼈장국",
    category: "한식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "K43",
    name: "정주보쌈",
    category: "한식",
    type: "식사",
    zone: "B",
    solo: true,
  },

  // ───────────────────────────────────────────────
  // ───────────────────────────────────────────────
  // 일식 (J1 ~ J20)
  // ───────────────────────────────────────────────
  // ───────────────────────────────────────────────

  {
    id: "J1",
    name: "라라유부 명지대 본점",
    category: "일식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "J2",
    name: "활구팔구",
    category: "일식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "J3",
    name: "3KG이상대광어횟집",
    category: "일식",
    type: "식사",
    zone: "C",
    solo: false,
  },
  {
    id: "J4",
    name: "왕포수산",
    category: "일식",
    type: "식사",
    zone: "C",
    solo: false,
  },
  {
    id: "J5",
    name: "긴자료코 명지대점",
    category: "일식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "J6",
    name: "스시하나에",
    category: "일식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "J7",
    name: "타코야끼 오늘",
    category: "일식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "J8",
    name: "여부초밥 명지대점",
    category: "일식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "J9",
    name: "가타쯔무리",
    category: "일식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "J10",
    name: "소소식탁 명지대",
    category: "일식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "J11",
    name: "만평우동 명지대점",
    category: "일식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "J12",
    name: "핵밥 명지대점",
    category: "일식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "J13",
    name: "육초연 명지대점",
    category: "일식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "J14",
    name: "화전",
    category: "일식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "J15",
    name: "김은수참치",
    category: "일식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "J16",
    name: "나라비",
    category: "일식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "J17",
    name: "아쯔다무라",
    category: "일식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "J18",
    name: "나베야 남가좌명지대점",
    category: "일식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "J19",
    name: "신 부산스시",
    category: "일식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "J20",
    name: "육회바른연어 명지대점",
    category: "일식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  // ───────────────────────────────────────────────
  // ───────────────────────────────────────────────
  // 중식 (J1 ~ J20)
  // ───────────────────────────────────────────────
  // ───────────────────────────────────────────────

  {
    id: "C1",
    name: "왕가주방",
    category: "중식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "C2",
    name: "춘리마라탕 명지대점",
    category: "중식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "C3",
    name: "마라왕마라탕",
    category: "중식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "C4",
    name: "라와마라탕 명지대점",
    category: "중식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "C5",
    name: "미르중식",
    category: "중식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "C6",
    name: "탕화쿵푸마라탕 명지대점",
    category: "중식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "C7",
    name: "유진반점",
    category: "중식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "C8",
    name: "진짜루",
    category: "중식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "C9",
    name: "다복향마라탕 명지대점",
    category: "중식",
    type: "식사",
    zone: "A",
    solo: true,
  },
  {
    id: "C10",
    name: "성연마라탕",
    category: "중식",
    type: "식사",
    zone: "A",
    solo: true,
  },
  {
    id: "C11",
    name: "샹츠마라 명지대점",
    category: "중식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "C12",
    name: "짜우반점",
    category: "중식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "C13",
    name: "완푸",
    category: "중식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "C14",
    name: "궁가",
    category: "중식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "C15",
    name: "중화루",
    category: "중식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "C16",
    name: "세아짬뽕",
    category: "중식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "C17",
    name: "성연양꼬치",
    category: "중식",
    type: "식사",
    zone: "B",
    solo: false,
  },
  {
    id: "C18",
    name: "미향만두전문점",
    category: "중식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "C19",
    name: "차푸 본점",
    category: "중식",
    type: "식사",
    zone: "B",
    solo: true,
  },

  // ───────────────────────────────────────────────
  // 고기 (M1 ~ M29)
  // ───────────────────────────────────────────────
  // {
  //   id: "M1",
  //   name: "명지대박창",
  //   category: "고기",
  //   type: "식사",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "M2",
  //   name: "꼬꼬아 닭먹자",
  //   category: "고기",
  //   type: "식사",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "M3",
  //   name: "고기구이마마치킨 명지대",
  //   category: "고기",
  //   type: "식사",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "M4",
  //   name: "삼겹아이트",
  //   category: "고기",
  //   type: "식사",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "M5",
  //   name: "큰손갈비 & 곱창 명지대점",
  //   category: "고기",
  //   type: "식사",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "M6",
  //   name: "깡통집",
  //   category: "고기",
  //   type: "식사",
  //   zone: "명지대 정문",
  // },
  // { id: "M7", name: "금정기", category: "고기", type: "식사", zone: "가좌역" },
  // {
  //   id: "M8",
  //   name: "홍가 족발집",
  //   category: "고기",
  //   type: "식사",
  //   zone: "가좌역",
  // },
  // {
  //   id: "M9",
  //   name: "우리통네 옛날 통닭",
  //   category: "고기",
  //   type: "식사",
  //   zone: "가좌역",
  // },
  // {
  //   id: "M10",
  //   name: "해피소금구이",
  //   category: "고기",
  //   type: "식사",
  //   zone: "가좌역",
  // },
  // { id: "M11", name: "장수촌", category: "고기", type: "식사", zone: "가좌역" },
  // {
  //   id: "M12",
  //   name: "삼겹베네 명지대점",
  //   category: "고기",
  //   type: "식사",
  //   zone: "가좌역",
  // },
  // {
  //   id: "M13",
  //   name: "60게치킨 명지대점",
  //   category: "고기",
  //   type: "식사",
  //   zone: "가좌역",
  // },
  // {
  //   id: "M14",
  //   name: "325새겹살",
  //   category: "고기",
  //   type: "식사",
  //   zone: "가좌역",
  // },
  // {
  //   id: "M15",
  //   name: "푸라닭 남가좌점",
  //   category: "고기",
  //   type: "식사",
  //   zone: "남가좌",
  // },
  // {
  //   id: "M16",
  //   name: "엄마손닭갈비",
  //   category: "고기",
  //   type: "식사",
  //   zone: "남가좌",
  // },
  // {
  //   id: "M17",
  //   name: "모래이곱창",
  //   category: "고기",
  //   type: "식사",
  //   zone: "남가좌",
  // },
  // {
  //   id: "M18",
  //   name: "KFC 명지대",
  //   category: "고기",
  //   type: "식사",
  //   zone: "남가좌",
  // },
  // {
  //   id: "M19",
  //   name: "족발신선생 남가좌명지대점",
  //   category: "고기",
  //   type: "식사",
  //   zone: "남가좌",
  // },
  // {
  //   id: "M20",
  //   name: "교촌치킨 명지대점",
  //   category: "고기",
  //   type: "식사",
  //   zone: "남가좌",
  // },
  // {
  //   id: "M21",
  //   name: "치킨나래 명지대점",
  //   category: "고기",
  //   type: "식사",
  //   zone: "남가좌",
  // },
  // {
  //   id: "M22",
  //   name: "왕십리곱창",
  //   category: "고기",
  //   type: "식사",
  //   zone: "남가좌",
  // },
  // {
  //   id: "M23",
  //   name: "살불엣날통 남가좌점",
  //   category: "고기",
  //   type: "식사",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "M24",
  //   name: "족발아시장 남가좌점",
  //   category: "고기",
  //   type: "식사",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "M25",
  //   name: "황제정육식당 명지대점",
  //   category: "고기",
  //   type: "식사",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "M26",
  //   name: "신돈갈비",
  //   category: "고기",
  //   type: "식사",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "M27",
  //   name: "다모식당",
  //   category: "고기",
  //   type: "식사",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "M28",
  //   name: "행운갈비",
  //   category: "고기",
  //   type: "식사",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "M29",
  //   name: "금네치킨 남가좌1호점",
  //   category: "고기",
  //   type: "식사",
  //   zone: "홍제 방면",
  // },

  // // ───────────────────────────────────────────────
  // // 주류 (A1 ~ A30)
  // // ───────────────────────────────────────────────
  // {
  //   id: "A1",
  //   name: "명지비어",
  //   category: "주류",
  //   type: "술집",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "A2",
  //   name: "투다리 하나로점",
  //   category: "주류",
  //   type: "술집",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "A3",
  //   name: "닭발집 명지대점",
  //   category: "주류",
  //   type: "술집",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "A4",
  //   name: "복가좌 거기",
  //   category: "주류",
  //   type: "술집",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "A5",
  //   name: "인뱅액주 명지대점",
  //   category: "주류",
  //   type: "술집",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "A6",
  //   name: "담너머",
  //   category: "주류",
  //   type: "술집",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "A7",
  //   name: "엑전할머니맥주 서울명지대점",
  //   category: "주류",
  //   type: "술집",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "A8",
  //   name: "골목",
  //   category: "주류",
  //   type: "술집",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "A9",
  //   name: "디진다",
  //   category: "주류",
  //   type: "술집",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "A10",
  //   name: "아키토리쿠모",
  //   category: "주류",
  //   type: "술집",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "A11",
  //   name: "엥이호프",
  //   category: "주류",
  //   type: "술집",
  //   zone: "남가좌",
  // },
  // {
  //   id: "A12",
  //   name: "학창시절",
  //   category: "주류",
  //   type: "술집",
  //   zone: "남가좌",
  // },
  // {
  //   id: "A13",
  //   name: "베로베로",
  //   category: "주류",
  //   type: "술집",
  //   zone: "남가좌",
  // },
  // { id: "A14", name: "수아레", category: "주류", type: "술집", zone: "남가좌" },
  // { id: "A15", name: "술짓사", category: "주류", type: "술집", zone: "남가좌" },
  // {
  //   id: "A16",
  //   name: "어나더라운드",
  //   category: "주류",
  //   type: "술집",
  //   zone: "남가좌",
  // },
  // {
  //   id: "A17",
  //   name: "네코노치킨",
  //   category: "주류",
  //   type: "술집",
  //   zone: "남가좌",
  // },
  // {
  //   id: "A18",
  //   name: "손가비반디떡",
  //   category: "주류",
  //   type: "술집",
  //   zone: "남가좌",
  // },
  // { id: "A19", name: "정든밥", category: "주류", type: "술집", zone: "남가좌" },
  // {
  //   id: "A20",
  //   name: "리얼밤 & 살얼음맥주 서울명지대점",
  //   category: "주류",
  //   type: "술집",
  //   zone: "남가좌",
  // },
  // {
  //   id: "A21",
  //   name: "완숙",
  //   category: "주류",
  //   type: "술집",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "A22",
  //   name: "카페나리",
  //   category: "주류",
  //   type: "술집",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "A23",
  //   name: "실내포치123",
  //   category: "주류",
  //   type: "술집",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "A24",
  //   name: "봄비달빛아래",
  //   category: "주류",
  //   type: "술집",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "A25",
  //   name: "투다리 명지대점",
  //   category: "주류",
  //   type: "술집",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "A26",
  //   name: "오늘은한잔해",
  //   category: "주류",
  //   type: "술집",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "A27",
  //   name: "아키토리지층",
  //   category: "주류",
  //   type: "술집",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "A28",
  //   name: "명지호프",
  //   category: "주류",
  //   type: "술집",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "A29",
  //   name: "와다이야카아",
  //   category: "주류",
  //   type: "술집",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "A30",
  //   name: "명승이포차",
  //   category: "주류",
  //   type: "술집",
  //   zone: "홍제 방면",
  // },

  // // ───────────────────────────────────────────────
  // // 카페·디저트 (D1 ~ D53)
  // // ───────────────────────────────────────────────
  // {
  //   id: "D1",
  //   name: "메가MGC커피 서울명지점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "D2",
  //   name: "카페뚜시",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "D3",
  //   name: "디저트39 명지대점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "D4",
  //   name: "평통와을 명지대점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "D5",
  //   name: "아린카페",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "D6",
  //   name: "비긴 베이커리 구페",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "D7",
  //   name: "커피티",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "D8",
  //   name: "모다가기 카페",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "D9",
  //   name: "데니스커피 명지대점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "D10",
  //   name: "비릉",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "D11",
  //   name: "몰센",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "D12",
  //   name: "크레이프",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "D13",
  //   name: "백억카피 가좌점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "D14",
  //   name: "팔곤디 명지전문대점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "D15",
  //   name: "봄맨선",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "D16",
  //   name: "카페레빈",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "명지대 정문",
  // },
  // {
  //   id: "D17",
  //   name: "일규벌사추려스",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "가좌역",
  // },
  // {
  //   id: "D18",
  //   name: "Y3S COFFEE",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "가좌역",
  // },
  // {
  //   id: "D19",
  //   name: "시낫기에싱음나무",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "가좌역",
  // },
  // {
  //   id: "D20",
  //   name: "백다잉 명지대점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "가좌역",
  // },
  // {
  //   id: "D21",
  //   name: "크레마하브",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "가좌역",
  // },
  // {
  //   id: "D22",
  //   name: "카페인중독 명지대점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "가좌역",
  // },
  // {
  //   id: "D23",
  //   name: "이루",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "가좌역",
  // },
  // {
  //   id: "D24",
  //   name: "컵포즈커피 명지대점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "남가좌",
  // },
  // {
  //   id: "D25",
  //   name: "투썸플레이스 명지대점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "남가좌",
  // },
  // {
  //   id: "D26",
  //   name: "곱치 명지대점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "남가좌",
  // },
  // {
  //   id: "D27",
  //   name: "이디야커피 명지대점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "남가좌",
  // },
  // {
  //   id: "D28",
  //   name: "국민우유집 본점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "남가좌",
  // },
  // {
  //   id: "D29",
  //   name: "발루통 전치",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "남가좌",
  // },
  // {
  //   id: "D30",
  //   name: "오렐의 이유",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "남가좌",
  // },
  // {
  //   id: "D31",
  //   name: "플러스82 새대문점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "남가좌",
  // },
  // {
  //   id: "D32",
  //   name: "매머드익스프레스 명지대점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "남가좌",
  // },
  // {
  //   id: "D33",
  //   name: "스타벅스 명지대점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "남가좌",
  // },
  // {
  //   id: "D34",
  //   name: "설빙 명지대점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "남가좌",
  // },
  // {
  //   id: "D35",
  //   name: "컴포즈커피 명지대사거리점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "남가좌",
  // },
  // {
  //   id: "D36",
  //   name: "메가MGC커피 명지대점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "D37",
  //   name: "프린누아",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "D38",
  //   name: "베스킨라빈스 남가좌점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "D39",
  //   name: "와플대학 명지대캠퍼스",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "D40",
  //   name: "카페 만월명 명지대점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "D41",
  //   name: "베이커리P67",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "D42",
  //   name: "비콘즈",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "D43",
  //   name: "씩띵크",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "D44",
  //   name: "하이흠 디저트",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "D45",
  //   name: "곰돌다방",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "D46",
  //   name: "갈이가치",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "D47",
  //   name: "쓰내디",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "D48",
  //   name: "셀렉토커피 남가좌점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "D49",
  //   name: "요거트파를 명지대점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "D50",
  //   name: "파리바게뜨 명지대점",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "D51",
  //   name: "노봄베이커리",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "D52",
  //   name: "스마일일용돔찰쌀떡빵기",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "홍제 방면",
  // },
  // {
  //   id: "D53",
  //   name: "24시 무인 달카페",
  //   category: "카페·디저트",
  //   type: "카페",
  //   zone: "홍제 방면",
  // },

  // ───────────────────────────────────────────────
  // 양식·아시안 (W1 ~ W12)
  // ───────────────────────────────────────────────

  {
    id: "W1",
    name: "빨간토마토피자본점",
    category: "양식·아시안",
    type: "식사",
    zone: "C",
    solo: false,
  },
  {
    id: "W2",
    name: "리코",
    category: "양식·아시안",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "W3",
    name: "피자스쿨 명지대점",
    category: "양식·아시안",
    type: "식사",
    zone: "C",
    solo: false,
  },
  {
    id: "W4",
    name: "베트남쌀국수포녹",
    category: "양식·아시안",
    type: "식사",
    zone: "A",
    solo: true,
  },
  {
    id: "W5",
    name: "명지샤브",
    category: "양식·아시안",
    type: "식사",
    zone: "A",
    solo: true,
  },
  {
    id: "W6",
    name: "꾸오레 베로",
    category: "양식·아시안",
    type: "식사",
    zone: "A",
    solo: true,
  },
  {
    id: "W7",
    name: "피나치공 서대문홍은점",
    category: "양식·아시안",
    type: "식사",
    zone: "A",
    solo: false,
  },
  {
    id: "W8",
    name: "주인백 파스타",
    category: "양식·아시안",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "W9",
    name: "타코볼볼 명지대점",
    category: "양식·아시안",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "W10",
    name: "밀",
    category: "양식·아시안",
    type: "식사",
    zone: "B",
    solo: false,
  },
  {
    id: "W11",
    name: "미분당 가좌점",
    category: "양식·아시안",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "W12",
    name: "라온아토",
    category: "양식·아시안",
    type: "식사",
    zone: "B",
    solo: false,
  },
  {
    id: "F1",
    name: "본도시락 명지대점",
    category: "간편식·분식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "F2",
    name: "김밥천국 명지점",
    category: "간편식·분식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "F3",
    name: "허니돈 명지대점",
    category: "간편식·분식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "F4",
    name: "리코브리또",
    category: "간편식·분식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "F5",
    name: "응급실떡볶이 남가좌점",
    category: "간편식·분식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "F6",
    name: "미소떡볶이",
    category: "간편식·분식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "F7",
    name: "행복한떡볶이",
    category: "간편식·분식",
    type: "식사",
    zone: "C",
    solo: true,
  },
  {
    id: "F8",
    name: "얌얌샐러드",
    category: "간편식·분식",
    type: "식사",
    zone: "A",
    solo: true,
  },
  {
    id: "F9",
    name: "순이네고릴라떡볶이본점",
    category: "간편식·분식",
    type: "식사",
    zone: "A",
    solo: true,
  },
  {
    id: "F10",
    name: "써브웨이 명지대점",
    category: "간편식·분식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "F11",
    name: "맥도날드 명지대점",
    category: "간편식·분식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "F12",
    name: "한솥도시락 명지대앞점",
    category: "간편식·분식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "F13",
    name: "슬로우캘리 명지대점",
    category: "간편식·분식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "F14",
    name: "롯데리아 명지대학점",
    category: "간편식·분식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "F15",
    name: "동대문엽기떡볶이 명지대점",
    category: "간편식·분식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "F16",
    name: "신전떡볶이 명지대점",
    category: "간편식·분식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "F17",
    name: "엄마손떡볶이",
    category: "간편식·분식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "F18",
    name: "더김밥 명지대점",
    category: "간편식·분식",
    type: "식사",
    zone: "정문",
    solo: true,
  },
  {
    id: "F19",
    name: "이삭토스트 명지대점",
    category: "간편식·분식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "F20",
    name: "맘스터치 명지대점",
    category: "간편식·분식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "F21",
    name: "만두성지",
    category: "간편식·분식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "F22",
    name: "스텔라떡볶이 서울명지대점",
    category: "간편식·분식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "F23",
    name: "어글리김밥",
    category: "간편식·분식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "F24",
    name: "호시타코야끼 명지대점",
    category: "간편식·분식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "F25",
    name: "왕만두 쉐프 명지대점",
    category: "간편식·분식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "F26",
    name: "하나네김밥",
    category: "간편식·분식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "F27",
    name: "이정희떡볶이",
    category: "간편식·분식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "F28",
    name: "담꾹 남가좌점",
    category: "간편식·분식",
    type: "식사",
    zone: "B",
    solo: true,
  },
  {
    id: "F29",
    name: "호호키친",
    category: "간편식·분식",
    type: "식사",
    zone: "B",
    solo: true,
  },
];
