export interface Restaurant {
  id: string;
  name: string;
  category:
    | "한식"
    | "일식"
    | "중식"
    | "간편식·분식"
    | "고기"
    | "양식·아시안"
    | "주류"
    | "카페·디저트"
    | "종합"; // '종합' 카테고리 추가 (필요시)
  type: "식사" | "술집" | "카페";
  zone: "정문" | "A" | "B" | "C";
  solo: boolean;
  address: string;
  roadAddress: string;
  mapx: string;
  mapy: string;
  lat: number;
  lng: number;

  // --- 신규 추가 필드 ---

  /** 네이버 지도 연결 링크 */
  naverMapCode: number;

  /** * 가게 단위의 핵심 필터 상태
   * (지도에서 전체 가게를 필터링할 때 사용)
   */
  filters: {
    isCheap: boolean; // 저렴이 (8000원 전후)
    isHighProtein: boolean; // 고단백
    isHealthy: boolean; // 건강식
  };

  /** * 다국어 지원을 위한 메뉴 리스트
   * (확장성을 위해 배열로 구성)
   */
  minPrice: number | null; // 최저가 (필터링용)
  menus: Menu[];
}

export interface Menu {
  menuId: string;
  isPrimary?: boolean; // 지도 마커에 표시할 대표 메뉴 여부
  price?: number; // 최저가 및 필터링용 가격
  /** 다국어 지원 메뉴명 */
  name: {
    ko: string;
    en: string;
    zh: string;
    ja: string;
    vi: string;
  };

  /** 메뉴별 세부 태그 (선택 사항) */
  tags?: string[];
}

export const restaurants: Restaurant[] = [
  // ───────────────────────────────────────────────
  // 한식 (K1 ~ K43)
  // ───────────────────────────────────────────────
  {
    id: "K1",
    name: "부안식당",
    category: "한식",
    type: "식사",
    zone: "C",
    solo: false,
    address: "서울특별시 서대문구 남가좌동 8-14",
    roadAddress: "서울특별시 서대문구 명지대길 68-1",
    mapx: "1269234763",
    mapy: "375831068",
    lat: 37.5831122,
    lng: 126.9234998,
    naverMapCode: 13150835,
    minPrice: 8000,
    filters: { isCheap: true, isHighProtein: true, isHealthy: false },
    menus: [
      {
        menuId: "1",
        isPrimary: true,
        price: 8000,
        name: {
          ko: "백반",
          en: "Set Menu",
          zh: "韩式定食",
          ja: "定食",
          vi: "Suất ăn cơm trắng",
        },
      },
      {
        menuId: "2",
        isPrimary: true,
        price: 8000,
        name: {
          ko: "순대국",
          en: "Blood Sausage Soup",
          zh: "血肠汤",
          ja: "スンデク",
          vi: "Canh dồi lợn",
        },
      },
      {
        menuId: "3",
        isPrimary: true,
        price: 8000,
        name: {
          ko: "순두부",
          en: "Soft Tofu Stew",
          zh: "嫩豆腐汤",
          ja: "スンドゥブ",
          vi: "Canh đậu phụ non",
        },
      },
      {
        menuId: "4",
        isPrimary: true,
        price: 8000,
        name: {
          ko: "된장찌개",
          en: "Soybean Paste Stew",
          zh: "大酱汤",
          ja: "味噌チゲ",
          vi: "Canh tương đậu",
        },
      },
      {
        menuId: "5",
        isPrimary: true,
        price: 8000,
        name: {
          ko: "청국장",
          en: "Rich Soybean Paste Stew",
          zh: "清鞠酱汤",
          ja: "チョングッチャン",
          vi: "Canh Cheonggukjang",
        },
      },
      {
        menuId: "6",
        isPrimary: true,
        price: 9000,
        name: {
          ko: "고추장불고기",
          en: "Spicy Pork Bulgogi",
          zh: "辣椒酱炒猪肉",
          ja: "コチュジャンプルコギ",
          vi: "Thịt lợn xào cay",
        },
      },
      {
        menuId: "7",
        isPrimary: true,
        price: 10000,
        name: {
          ko: "생선구이 (고등어)",
          en: "Grilled Mackerel",
          zh: "烤青花鱼",
          ja: "焼き魚 (サバ)",
          vi: "Cá thu nướng",
        },
      },
      {
        menuId: "8",
        isPrimary: true,
        price: 20000,
        name: {
          ko: "갈비정식 (2인 기준)",
          en: "Galbi Set (for 2)",
          zh: "排骨定食 (2人份)",
          ja: "カルビ定食 (2人基準)",
          vi: "Suất sườn nướng (cho 2 người)",
        },
      },
      {
        menuId: "9",
        isPrimary: true,
        price: 10000,
        name: {
          ko: "뚝배기불고기",
          en: "Bulgogi in a Hot Stone Pot",
          zh: "砂锅烤肉",
          ja: "トゥッペギプルコギ",
          vi: "Thịt bò xào nồi đất",
        },
      },
      {
        menuId: "10",
        isPrimary: true,
        price: 20000,
        name: {
          ko: "김치찌개 (2인)",
          en: "Kimchi Stew (for 2)",
          zh: "泡菜汤 (2人份)",
          ja: "キムチチゲ (2人)",
          vi: "Canh Kimchi (cho 2 người)",
        },
      },
    ],
  },
  {
    id: "K2",
    name: "대한카츠 서대문점(구 차고집칡냉면)",
    category: "일식",
    type: "식사",
    zone: "C",
    solo: false,
    address: "서울특별시 서대문구 남가좌동 3-2",
    roadAddress: "서울특별시 서대문구 남가좌동 명지대길 83",
    mapx: "1269230866",
    mapy: "375837415",
    lat: 37.583558,
    lng: 126.923026,
    naverMapCode: 1958140702, // 미기입
    minPrice: null,
    filters: { isCheap: false, isHighProtein: true, isHealthy: false },
    menus: [
      {
        menuId: "1",
        isPrimary: true,
        name: {
          ko: "돈카츠",
          en: "Donkatsu",
          zh: "炸猪排",
          ja: "とんかつ",
          vi: "Thịt lợn chiên xù",
        },
      },
    ],
  },
  {
    id: "K9",
    name: "한술식당 명지대점",
    category: "한식",
    type: "식사",
    zone: "C",
    solo: true,
    address: "서울특별시 서대문구 홍은동 401-12 1층",
    roadAddress: "서울특별시 서대문구 명지대2길 2 1층",
    mapx: "1269250620",
    mapy: "375813952",
    lat: 37.5813881,
    lng: 126.9250928,
    naverMapCode: 1945558222,
    minPrice: 10900,
    filters: { isCheap: false, isHighProtein: true, isHealthy: false },
    menus: [
      {
        menuId: "1",
        isPrimary: true,
        price: 16900,
        name: {
          ko: "고추장 한우 대창 덮밥",
          en: "Gochujang Beef Intestine Rice Bowl",
          zh: "辣酱韩우大肠盖饭",
          ja: "コチュジャン韓牛ホルモン丼",
          vi: "Cơm trộn lòng bò Hanwoo sốt Gochujang",
        },
      },
      {
        menuId: "2",
        isPrimary: true,
        price: 13900,
        name: {
          ko: "간장 닭목살 덮밥",
          en: "Soy Sauce Chicken Neck Meat Rice Bowl",
          zh: "酱油鸡颈肉盖饭",
          ja: "醤油鶏せせり丼",
          vi: "Cơm trộn thịt cổ gà sốt tương",
        },
      },
      {
        menuId: "3",
        isPrimary: true,
        price: 11900,
        name: {
          ko: "간장 삼겹 덮밥",
          en: "Soy Sauce Pork Belly Rice Bowl",
          zh: "酱油五花肉盖饭",
          ja: "醤油豚バラ丼",
          vi: "Cơm trộn thịt ba chỉ sốt tương",
        },
      },
      {
        menuId: "4",
        isPrimary: true,
        price: 10900,
        name: {
          ko: "간장 닭고기 덮밥",
          en: "Soy Sauce Chicken Rice Bowl",
          zh: "酱油鸡肉盖饭",
          ja: "醤油鶏肉丼",
          vi: "Cơm trộn thịt gà sốt tương",
        },
      },
      {
        menuId: "5",
        isPrimary: true,
        price: 11900,
        name: {
          ko: "고추장 삼겹 덮밥",
          en: "Gochujang Pork Belly Rice Bowl",
          zh: "辣酱五花肉盖饭",
          ja: "コチュジャン豚バラ丼",
          vi: "Cơm trộn thịt ba chỉ sốt Gochujang",
        },
      },
      {
        menuId: "6",
        isPrimary: true,
        price: 10900,
        name: {
          ko: "닭갈비 덮밥",
          en: "Spicy Stir-fried Chicken Rice Bowl",
          zh: "辣炒鸡排盖饭",
          ja: "タッカルビ丼",
          vi: "Cơm trộn gà xào cay (Dak-galbi)",
        },
      },
      {
        menuId: "7",
        isPrimary: true,
        price: 11900,
        name: {
          ko: "치즈 닭갈비 덮밥",
          en: "Cheese Spicy Stir-fried Chicken Rice Bowl",
          zh: "芝士辣炒鸡排盖饭",
          ja: "チーズタッカルビ丼",
          vi: "Cơm trộn gà xào cay phô mai",
        },
      },
      {
        menuId: "8",
        isPrimary: true,
        price: 10900,
        name: {
          ko: "제육 덮밥",
          en: "Spicy Pork Rice Bowl",
          zh: "辣炒猪肉盖饭",
          ja: "豚肉炒め丼 (ジェユクドッパプ)",
          vi: "Cơm trộn thịt lợn xào cay",
        },
      },
      {
        menuId: "9",
        isPrimary: true,
        price: 11900,
        name: {
          ko: "치즈 제육 덮밥",
          en: "Cheese Spicy Pork Rice Bowl",
          zh: "芝士辣炒猪肉盖饭",
          ja: "チーズ豚肉炒め丼",
          vi: "Cơm trộn thịt lợn xào cay phô mai",
        },
      },
      {
        menuId: "10",
        isPrimary: true,
        price: 13900,
        name: {
          ko: "가지 된장 마제 소바",
          en: "Eggplant Miso Maze Soba",
          zh: "茄子大酱拌荞麦面",
          ja: "茄子味噌まぜそば",
          vi: "Mì trộn Soba cà tím sốt tương 된장",
        },
      },
    ],
  },
  {
    id: "K24",
    name: "삼정식당",
    category: "한식",
    type: "식사",
    zone: "정문",
    solo: true,
    address: "서울특별시 서대문구 남가좌동 324-9 삼정식당",
    roadAddress: "서울특별시 서대문구 거북골로 25-8 삼정식당",
    mapx: "1269249254",
    mapy: "375796692",
    lat: 37.5796387,
    lng: 126.9249273,
    naverMapCode: 1025414098,
    minPrice: 6000,
    filters: { isCheap: true, isHighProtein: true, isHealthy: true },
    menus: [
      {
        menuId: "1",
        isPrimary: true,
        price: 6000,
        name: {
          ko: "아침한식뷔페",
          en: "Korean Breakfast Buffet",
          zh: "韩式早餐自助餐",
          ja: "韓国式朝食ビュッフェ",
          vi: "Buffet sáng món Hàn",
        },
      },
      {
        menuId: "2",
        isPrimary: true,
        price: 9000,
        name: {
          ko: "점심한식뷔페",
          en: "Korean Dinner Buffet",
          zh: "韩式晚餐自助餐",
          ja: "韓国式夕食ビュッフェ",
          vi: "Buffet tối món Hàn",
        },
      },
    ],
  },
  {
    id: "K42",
    name: "대가감자탕뼈해장국",
    category: "한식",
    type: "식사",
    zone: "B",
    solo: true,
    address: "서울특별시 서대문구 남가좌동 338-39",
    roadAddress: "서울특별시 서대문구 증가로 111",
    mapx: "1269249207",
    mapy: "375766479",
    lat: 37.5766538,
    lng: 126.9248759,
    naverMapCode: 0,
    minPrice: 11000,
    filters: { isCheap: false, isHighProtein: true, isHealthy: false },
    menus: [
      {
        menuId: "1",
        isPrimary: true,
        price: 45000,
        name: {
          ko: "한상세트",
          en: "Hansang Set (Gamjatang & Bossam & Oyster)",
          zh: "一桌套餐",
          ja: "ハンサンセット",
          vi: "Set Hansang",
        },
      },
      {
        menuId: "2",
        isPrimary: true,
        price: 34000,
        name: {
          ko: "대가감자탕",
          en: "Daega Pork Back Rib Stew",
          zh: "大家土豆汤",
          ja: "テガカムジャタン",
          vi: "Lẩu xương heo Daega",
        },
      },
      {
        menuId: "3",
        isPrimary: true,
        price: 29000,
        name: {
          ko: "대가보쌈",
          en: "Daega Bossam (Napa Wraps with Pork)",
          zh: "大家菜包肉",
          ja: "テガポッサム",
          vi: "Thịt heo luộc Daega",
        },
      },
      {
        menuId: "4",
        isPrimary: true,
        price: 11000,
        name: {
          ko: "뼈해장국",
          en: "Pork Spine Hangover Soup",
          zh: "土豆排骨解酒汤",
          ja: "ピョヘジャンクク",
          vi: "Canh xương heo giải rượu",
        },
      },
      {
        menuId: "5",
        isPrimary: true,
        price: 13000,
        name: {
          ko: "우거지내장탕",
          en: "Dried Cabbage and Beef Tripe Soup",
          zh: "干菜内脏汤",
          ja: "ウゴジホルモン湯",
          vi: "Canh lòng bò rau cải khô",
        },
      },
      {
        menuId: "6",
        isPrimary: true,
        price: 13000,
        name: {
          ko: "보쌈정식",
          en: "Bossam Set Menu",
          zh: "菜包肉定食",
          ja: "ポッサム定食",
          vi: "Cơm suất thịt heo luộc",
        },
      },
      {
        menuId: "7",
        isPrimary: true,
        price: 10000,
        name: {
          ko: "선지해장국",
          en: "Ox Blood Hangover Soup",
          zh: "牛血解酒汤",
          ja: "ソンジヘジャンクク",
          vi: "Canh huyết bò giải rượu",
        },
      },
    ],
  },
  {
    id: "K3",
    name: "치즈밥있슈명지대점",
    category: "한식",
    type: "식사",
    zone: "C",
    solo: true,
    address: "서울특별시 서대문구 남가좌동 7-2",
    roadAddress: "서울특별시 서대문구 명지대길 62",
    mapx: "1269236049",
    mapy: "375827889",
    lat: 37.5828048,
    lng: 126.9236117,
    naverMapCode: 31222381,
    minPrice: 7000,
    filters: { isCheap: true, isHighProtein: false, isHealthy: false },
    menus: [
      {
        menuId: "1",
        isPrimary: true,
        price: 5500,
        name: {
          ko: "갈비김치",
          en: "Galbi Kimchi Rice Bowl",
          zh: "排骨泡菜饭",
          ja: "カルビキムチ飯",
          vi: "Cơm trộn Galbi Kimchi",
        },
      },
      {
        menuId: "2",
        isPrimary: true,
        price: 7000,
        name: {
          ko: "갈비베이컨치즈밥",
          en: "Galbi Bacon Cheese Rice",
          zh: "排骨培根芝士饭",
          ja: "カルビベーコンチーズ飯",
          vi: "Cơm phô mai Galbi thịt xông khói",
        },
      },
      {
        menuId: "3",
        isPrimary: true,
        price: 7000,
        name: {
          ko: "카레베이컨치즈밥",
          en: "Curry Bacon Cheese Rice",
          zh: "咖喱培根芝士饭",
          ja: "カレーベーコンチーズ飯",
          vi: "Cơm phô mai cà ri thịt xông khói",
        },
      },
      {
        menuId: "4",
        isPrimary: true,
        price: 7000,
        name: {
          ko: "베이컨알치즈밥",
          en: "Bacon Fish Roe Cheese Rice",
          zh: "培根鱼子芝士饭",
          ja: "ベーコンとびっこチーズ飯",
          vi: "Cơm phô mai trứng cá thịt xông khói",
        },
      },
      {
        menuId: "5",
        isPrimary: true,
        price: 7000,
        name: {
          ko: "김치고구마치즈밥",
          en: "Kimchi Sweet Potato Cheese Rice",
          zh: "泡菜地瓜芝士饭",
          ja: "キム치さつまいもチーズ飯",
          vi: "Cơm phô mai Kimchi khoai lang",
        },
      },
      {
        menuId: "6",
        isPrimary: true,
        price: 7000,
        name: {
          ko: "떡갈비치즈밥",
          en: "Tteok-galbi Cheese Rice",
          zh: "烤肉饼芝士饭",
          ja: "トッカルビチーズ飯",
          vi: "Cơm phô mai Tteok-galbi",
        },
      },
    ],
  },
  {
    id: "K4",
    name: "수인김치찜",
    category: "한식",
    type: "식사",
    zone: "C",
    solo: true,
    address: "서울특별시 서대문구 남가좌동 5-179 제자교회",
    roadAddress: "서울특별시 서대문구 명지대1라길 2 제자교회",
    mapx: "1269237052",
    mapy: "375820715",
    lat: 37.5820863,
    lng: 126.9236537,
    naverMapCode: 35781718,
    minPrice: 7000,
    filters: { isCheap: true, isHighProtein: true, isHealthy: false },
    menus: [
      {
        menuId: "1",
        isPrimary: true,
        price: 8000,
        name: {
          ko: "맛있는 김치전골(김치+야채+버섯+고기)",
          en: "Delicious Kimchi Hot Pot (Kimchi, Veggies, Mushroom, Meat)",
          zh: "美味泡菜火锅 (含蔬菜、蘑菇、肉)",
          ja: "美味しいキムチチゲ (キムチ+野菜+きのこ+肉)",
          vi: "Lẩu Kimchi thập cẩm (Kimchi, rau, nấm, thịt)",
        },
      },
      {
        menuId: "2",
        isPrimary: true,
        price: 11000,
        name: {
          ko: "든든한 고기김치찜",
          en: "Hearty Braised Kimchi with Pork",
          zh: "肉片炖泡菜",
          ja: "たっぷり肉キムチ蒸し",
          vi: "Kimchi hấp thịt heo đậm đà",
        },
      },
      {
        menuId: "3",
        isPrimary: true,
        price: 7000,
        name: {
          ko: "깔끔한 김치전골(김치+야채+버섯)",
          en: "Clean Kimchi Hot Pot (Kimchi, Veggies, Mushroom)",
          zh: "清爽泡菜火锅 (含蔬菜、蘑菇)",
          ja: "さっぱりキムチチゲ (キムチ+野菜+きのこ)",
          vi: "Lẩu Kimchi thanh đạm (Kimchi, rau, nấm)",
        },
      },
      {
        menuId: "4",
        isPrimary: true,
        price: 8000,
        name: {
          ko: "뚝배기 불고기",
          en: "Bulgogi in a Hot Stone Pot",
          zh: "砂锅烤肉",
          ja: "トゥッペギプルコギ",
          vi: "Bulgogi nồi đất",
        },
      },
      {
        menuId: "5",
        isPrimary: true,
        price: 7000,
        name: {
          ko: "김치 칼국수",
          en: "Kimchi Kal-guksu (Chopped Noodle Soup)",
          zh: "泡菜刀切面",
          ja: "キムチカルグクス",
          vi: "Mì Kalguksu Kimchi",
        },
      },
    ],
  },
  {
    id: "K6",
    name: "화화매운갈비찜 & 소불고기버섯전골 명지대점",
    category: "한식",
    type: "식사",
    zone: "C",
    solo: true,
    address: "서울특별시 서대문구 홍은동 421-27",
    roadAddress: "서울특별시 서대문구 명지대길 34",
    mapx: "1269246088",
    mapy: "375818125",
    lat: 37.5818366,
    lng: 126.9246201,
    naverMapCode: 1295326911,
    minPrice: 22000,
    filters: { isCheap: false, isHighProtein: true, isHealthy: true },
    menus: [
      {
        menuId: "1",
        isPrimary: true,
        price: 33000,
        name: {
          ko: "동해해물탕",
          en: "Donghae Seafood Stew",
          zh: "东海海鲜汤",
          ja: "東海海鮮鍋",
          vi: "Lẩu hải sản Donghae",
        },
      },
      {
        menuId: "2",
        isPrimary: true,
        price: 33000,
        name: {
          ko: "동해해물찜",
          en: "Donghae Braised Seafood",
          zh: "东海蒸海鲜",
          ja: "東海海鮮蒸し",
          vi: "Hải sản hấp Donghae",
        },
      },
      {
        menuId: "3",
        isPrimary: true,
        price: 33000,
        name: {
          ko: "아구찜",
          en: "Braised Spicy Monkfish",
          zh: "辣炖 안康鱼",
          ja: "アグチム",
          vi: "Cá lồng hấp cay",
        },
      },
      {
        menuId: "4",
        isPrimary: true,
        price: 33000,
        name: {
          ko: "꽃게탕",
          en: "Blue Crab Stew",
          zh: "花蟹汤",
          ja: "ワタリガニ鍋",
          vi: "Lẩu cua",
        },
      },
      {
        menuId: "5",
        isPrimary: true,
        price: 33000,
        name: {
          ko: "꽃게찜",
          en: "Braised Blue Crab",
          zh: "蒸花蟹",
          ja: "ワタリガニ蒸し",
          vi: "Cua hấp",
        },
      },
      {
        menuId: "6",
        isPrimary: true,
        price: 33000,
        name: {
          ko: "낙지볶음",
          en: "Stir-fried Octopus",
          zh: "炒章鱼",
          ja: "ナクチポックム",
          vi: "Bạch tuộc xào cay",
        },
      },
      {
        menuId: "7",
        isPrimary: true,
        price: 15000,
        name: {
          ko: "알탕",
          en: "Spicy Fish Roe Soup",
          zh: "鱼卵汤",
          ja: "アルタン",
          vi: "Canh trứng cá",
        },
      },
      {
        menuId: "8",
        isPrimary: true,
        price: 11000,
        name: {
          ko: "동태탕",
          en: "Pollack Stew",
          zh: "冻明太鱼汤",
          ja: "スケトウダラ鍋",
          vi: "Canh cá minh thái",
        },
      },
      {
        menuId: "9",
        isPrimary: true,
        price: 13000,
        name: {
          ko: "회덮밥",
          en: "Raw Fish Bibimbap",
          zh: "生鱼片 盖饭",
          ja: "フェドッパプ",
          vi: "Cơm trộn cá sống",
        },
      },
      {
        menuId: "10",
        isPrimary: true,
        price: 10000,
        name: {
          ko: "전복죽",
          en: "Abalone Porridge",
          zh: "鲍鱼粥",
          ja: "全鮑粥",
          vi: "Cháo bào ngư",
        },
      },
      {
        menuId: "11",
        isPrimary: true,
        price: 13000,
        name: {
          ko: "물회",
          en: "Cold Raw Fish Soup",
          zh: "水脍",
          ja: "ムルフェ",
          vi: "Gỏi cá lạnh",
        },
      },
      {
        menuId: "12",
        isPrimary: true,
        price: 11000,
        name: {
          ko: "고등어구이",
          en: "Grilled Mackerel",
          zh: "烤青花鱼",
          ja: "サバ焼き",
          vi: "Cá thu nướng",
        },
      },
      {
        menuId: "13",
        isPrimary: true,
        price: 11000,
        name: {
          ko: "삼치구이",
          en: "Grilled Spanish Mackerel",
          zh: "烤鲅鱼",
          ja: "サワラ焼き",
          vi: "Cá thu đao nướng",
        },
      },
    ],
  },
  {
    id: "K7",
    name: "쏘울푸드",
    category: "한식",
    type: "식사",
    zone: "C",
    solo: true,
    address: "서울특별시 서대문구 홍은동 401-1 1층 103호 쏘울푸드",
    roadAddress: "서울특별시 서대문구 명지대2길 14 1층 103호 쏘울푸드",
    mapx: "1269251790",
    mapy: "375817442",
    lat: 37.5817967,
    lng: 126.9252269,
    naverMapCode: 1887405517,
    minPrice: 8000,
    filters: { isCheap: true, isHighProtein: true, isHealthy: true },
    menus: [
      {
        menuId: "1",
        isPrimary: true,
        price: 15000,
        name: {
          ko: "스테이크 덮밥",
          en: "Steak Rice Bowl",
          zh: "牛排盖饭",
          ja: "ステーキ丼",
          vi: "Cơm bò bít tết",
        },
      },
      {
        menuId: "2",
        isPrimary: true,
        price: 13000,
        name: {
          ko: "연어 덮밥",
          en: "Salmon Rice Bowl (Sake-don)",
          zh: "三文鱼盖饭",
          ja: "サーモン丼",
          vi: "Cơm cá hồi (Sakedon)",
        },
      },
      {
        menuId: "3",
        isPrimary: true,
        price: 13000,
        name: {
          ko: "간장새우 덮밥",
          en: "Soy-marinated Shrimp Rice Bowl",
          zh: "酱油虾盖饭",
          ja: "カンジャンセウ丼",
          vi: "Cơm tôm ngâm tương",
        },
      },
      {
        menuId: "4",
        isPrimary: true,
        price: 10000,
        name: {
          ko: "우삼겹 덮밥",
          en: "Beef Short Plate Rice Bowl",
          zh: "牛五花盖饭",
          ja: "牛バラ丼",
          vi: "Cơm ba chỉ bò",
        },
      },
      {
        menuId: "5",
        isPrimary: true,
        price: 10000,
        name: {
          ko: "항정살 덮밥",
          en: "Pork Jowl Rice Bowl",
          zh: "松板肉盖饭",
          ja: "豚トロ丼",
          vi: "Cơm nạc nọng heo",
        },
      },
      {
        menuId: "6",
        isPrimary: true,
        price: 10000,
        name: {
          ko: "매콤삼겹 덮밥",
          en: "Spicy Pork Belly Rice Bowl",
          zh: "辣炒五花肉盖饭",
          ja: "辛口豚バラ丼",
          vi: "Cơm thịt ba chỉ cay",
        },
      },
      {
        menuId: "7",
        isPrimary: true,
        price: 9000,
        name: {
          ko: "치킨마요 덮밥",
          en: "Chicken Mayo Rice Bowl",
          zh: "鸡肉蛋黄酱盖饭",
          ja: "チキンマヨ丼",
          vi: "Cơm gà sốt Mayo",
        },
      },
    ],
  },
  // {
  //   id: "K8",
  //   name: "생선구이와 돈까스2",
  //   category: "한식",
  //   type: "식사",
  //   zone: "C",
  //   solo: true,
  //   address: "서울특별시 서대문구 홍은동 421-13",
  //   roadAddress: "서울특별시 서대문구 명지대2길 7",
  //   mapx: "1269249417",
  //   mapy: "375815893",
  //   lat: 37.5815876,
  //   lng: 126.9249446,
  //   naverMapCode: 774318560,
  //   minPrice: 8000,
  //   filters: { isCheap: true, isHighProtein: true, isHealthy: false },
  //   menus: [
  //     {
  //       menuId: "k8-m1",
  //       isPrimary: true,
  //       price: 8000,
  //       name: { ko: "돈까스", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k8-m2",
  //       isPrimary: true,
  //       price: 9000,
  //       name: { ko: "제육볶음", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K10",
  //   name: "투데이하우스",
  //   category: "한식",
  //   type: "식사",
  //   zone: "C",
  //   solo: true,
  //   address: "서울특별시 서대문구 홍은동 401-14",
  //   roadAddress: "서울특별시 서대문구 명지대길 16",
  //   mapx: "1269251189",
  //   mapy: "375810942",
  //   lat: 37.5810942,
  //   lng: 126.9251189,
  //   naverMapCode: 1671421502,
  //   minPrice: 4000,
  //   filters: { isCheap: true, isHighProtein: true, isHealthy: false },
  //   menus: [
  //     {
  //       menuId: "k10-m1",
  //       isPrimary: true,
  //       price: 4000,
  //       name: { ko: "라면", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k10-m2",
  //       isPrimary: true,
  //       price: 7000,
  //       name: { ko: "제육덮밥", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k10-m3",
  //       isPrimary: true,
  //       name: { ko: "찌개류", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K11",
  //   name: "대빈",
  //   category: "한식",
  //   type: "식사",
  //   zone: "C",
  //   solo: true,
  //   address: "서울특별시 서대문구 홍은동 401-43 1층",
  //   roadAddress: "서울특별시 서대문구 명지대길 14 1층",
  //   mapx: "1269250612",
  //   mapy: "375809632",
  //   lat: 37.580968,
  //   lng: 126.9251027,
  //   naverMapCode: 1854685128,
  //   minPrice: 11000,
  //   filters: { isCheap: false, isHighProtein: false, isHealthy: false },
  //   menus: [
  //     {
  //       menuId: "k11-m1",
  //       isPrimary: true,
  //       price: 11000,
  //       name: { ko: "백합칼국수", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k11-m2",
  //       isPrimary: true,
  //       price: 12000,
  //       name: { ko: "비빔칼국수", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k11-m3",
  //       isPrimary: true,
  //       name: { ko: "부추전", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K12",
  //   name: "밥은화 명지대점",
  //   category: "한식",
  //   type: "식사",
  //   zone: "C",
  //   solo: true,
  //   address: "서울특별시 서대문구 홍은동 401-16 1층 밥은화",
  //   roadAddress: "서울특별시 서대문구 거북골로 14 1층 밥은화",
  //   mapx: "1269255461",
  //   mapy: "375807786",
  //   lat: 37.5808695,
  //   lng: 126.9256787,
  //   naverMapCode: 1684083866,
  //   minPrice: 6000,
  //   filters: { isCheap: true, isHighProtein: true, isHealthy: false },
  //   menus: [
  //     {
  //       menuId: "k12-m1",
  //       isPrimary: true,
  //       name: { ko: "직화덮밥", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k12-m2",
  //       isPrimary: true,
  //       price: 6000,
  //       name: { ko: "마요덮밥", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K13",
  //   name: "보리향기 본점",
  //   category: "한식",
  //   type: "식사",
  //   zone: "C",
  //   solo: true,
  //   address: "서울특별시 서대문구 홍은동 400-38 1층",
  //   roadAddress: "서울특별시 서대문구 거북골로 8-4 1층",
  //   mapx: "1269260114",
  //   mapy: "375813189",
  //   lat: 37.581339,
  //   lng: 126.9260634,
  //   naverMapCode: 1609774904,
  //   minPrice: 12000,
  //   filters: { isCheap: false, isHighProtein: true, isHealthy: true },
  //   menus: [
  //     {
  //       menuId: "k13-m1",
  //       isPrimary: true,
  //       price: 12000,
  //       name: { ko: "보리밥", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k13-m2",
  //       isPrimary: true,
  //       name: { ko: "떡갈비", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k13-m3",
  //       isPrimary: true,
  //       name: { ko: "쭈꾸미", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k13-m4",
  //       isPrimary: true,
  //       name: { ko: "코다리", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k13-m5",
  //       isPrimary: false,
  //       name: { ko: "제육볶음", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K14",
  //   name: "소반",
  //   category: "한식",
  //   type: "식사",
  //   zone: "C",
  //   solo: true,
  //   address: "서울특별시 서대문구 홍은동 400-13 새솔빌딩 1층",
  //   roadAddress: "서울특별시 서대문구 거북골로 4 새솔빌딩 1층",
  //   mapx: "1269264695",
  //   mapy: "375813958",
  //   lat: 37.5814219,
  //   lng: 126.9264371,
  //   naverMapCode: 738794960,
  //   minPrice: 8000,
  //   filters: { isCheap: true, isHighProtein: false, isHealthy: true },
  //   menus: [
  //     {
  //       menuId: "k14-m1",
  //       isPrimary: true,
  //       price: 8000,
  //       name: { ko: "김치찌개", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k14-m2",
  //       isPrimary: true,
  //       name: { ko: "비빔밥", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K15",
  //   name: "동궁찜닭 명지대점",
  //   category: "한식",
  //   type: "식사",
  //   zone: "A",
  //   solo: false,
  //   address: "서울특별시 서대문구 홍은동 409-47",
  //   roadAddress: "서울특별시 서대문구 거북골로 19-1",
  //   mapx: "1269251604",
  //   mapy: "375801558",
  //   lat: 37.5802192,
  //   lng: 126.9251634,
  //   naverMapCode: 1028667705,
  //   minPrice: 18000,
  //   filters: { isCheap: false, isHighProtein: true, isHealthy: false },
  //   menus: [
  //     {
  //       menuId: "k15-m1",
  //       isPrimary: true,
  //       name: { ko: "찜닭", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k15-m2",
  //       isPrimary: true,
  //       name: { ko: "닭도리탕", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K16",
  //   name: "엄마밥상",
  //   category: "한식",
  //   type: "식사",
  //   zone: "A",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 229-4",
  //   roadAddress: "서울특별시 서대문구 가재울로14길 13",
  //   mapx: "1269212923",
  //   mapy: "375768116",
  //   lat: 37.5768361,
  //   lng: 126.9213087,
  //   naverMapCode: 1455376260,
  //   minPrice: null,
  //   filters: { isCheap: true, isHighProtein: false, isHealthy: true },
  //   menus: [
  //     {
  //       menuId: "k16-m1",
  //       isPrimary: true,
  //       name: { ko: "백반", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k16-m2",
  //       isPrimary: true,
  //       name: { ko: "김밥", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k16-m3",
  //       isPrimary: false,
  //       name: { ko: "라면", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k16-m4",
  //       isPrimary: true,
  //       name: { ko: "비빔밥", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K17",
  //   name: "쿡스",
  //   category: "한식",
  //   type: "식사",
  //   zone: "A",
  //   solo: true,
  //   address: "서울특별시 서대문구 홍은동 408-1",
  //   roadAddress: "서울특별시 서대문구 증가로10길 94",
  //   mapx: "1269266689",
  //   mapy: "375803965",
  //   lat: 37.5803965,
  //   lng: 126.9266689,
  //   naverMapCode: 1101669100,
  //   minPrice: 9000,
  //   filters: { isCheap: false, isHighProtein: false, isHealthy: true },
  //   menus: [
  //     {
  //       menuId: "k17-m1",
  //       isPrimary: true,
  //       price: 9000,
  //       name: { ko: "백반", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k17-m2",
  //       isPrimary: true,
  //       name: { ko: "칼국수", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k17-m3",
  //       isPrimary: true,
  //       name: { ko: "비빔밥(여름)", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k17-m4",
  //       isPrimary: true,
  //       name: { ko: "국수(여름)", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K18",
  //   name: "민스키친",
  //   category: "한식",
  //   type: "식사",
  //   zone: "A",
  //   solo: false,
  //   address: "서울특별시 서대문구 홍은동 402-17",
  //   roadAddress: "서울특별시 서대문구 가좌로 89",
  //   mapx: "1269273291",
  //   mapy: "375808813",
  //   lat: 37.5808823,
  //   lng: 126.927288,
  //   naverMapCode: 1095063492,
  //   minPrice: null,
  //   filters: { isCheap: false, isHighProtein: true, isHealthy: false },
  //   menus: [
  //     {
  //       menuId: "k18-m1",
  //       isPrimary: true,
  //       name: { ko: "김치찜", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K19",
  //   name: "마닐로우 본점",
  //   category: "한식",
  //   type: "식사",
  //   zone: "정문",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 324-49 1층",
  //   roadAddress: "서울특별시 서대문구 거북골로 37-5 1층",
  //   mapx: "1269239080",
  //   mapy: "375791734",
  //   lat: 37.5791734,
  //   lng: 126.923908,
  //   naverMapCode: 1921315424,
  //   minPrice: 7900,
  //   filters: { isCheap: true, isHighProtein: true, isHealthy: true },
  //   menus: [
  //     {
  //       menuId: "k19-m1",
  //       isPrimary: true,
  //       price: 7900,
  //       name: { ko: "육회비빔밥", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k19-m2",
  //       isPrimary: true,
  //       price: 8900,
  //       name: { ko: "연어비빔밥", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K20",
  //   name: "베가 보쌈 명지대점",
  //   category: "한식",
  //   type: "식사",
  //   zone: "정문",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 324-42",
  //   roadAddress: "서울특별시 서대문구 거북골로 33-4",
  //   mapx: "1269240284",
  //   mapy: "375792414",
  //   lat: 37.5792567,
  //   lng: 126.9240279,
  //   naverMapCode: 1102427977,
  //   minPrice: 10000,
  //   filters: { isCheap: false, isHighProtein: true, isHealthy: false },
  //   menus: [
  //     {
  //       menuId: "k20-m1",
  //       isPrimary: true,
  //       price: 10000,
  //       name: { ko: "보쌈", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },

  // {
  //   id: "K21",
  //   name: "청춘보쌈",
  //   category: "한식",
  //   type: "식사",
  //   zone: "정문",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 325-15 2층",
  //   roadAddress: "서울특별시 서대문구 증가로10길 38 2층",
  //   mapx: "1269242844",
  //   mapy: "375788381",
  //   lat: 37.5788381,
  //   lng: 126.9242844,
  //   naverMapCode: 1326644451,
  //   minPrice: 9000,
  //   filters: { isCheap: false, isHighProtein: true, isHealthy: false },
  //   menus: [
  //     {
  //       menuId: "k21-m1",
  //       isPrimary: true,
  //       price: 9000,
  //       name: { ko: "보쌈", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K22",
  //   name: "봉구네가마솥순대국",
  //   category: "한식",
  //   type: "식사",
  //   zone: "정문",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 325-2",
  //   roadAddress: "서울특별시 서대문구 증가로10길 50",
  //   mapx: "1269247584",
  //   mapy: "375791807",
  //   lat: 37.5791649,
  //   lng: 126.9247804,
  //   naverMapCode: 36417234,
  //   minPrice: 9000,
  //   filters: { isCheap: false, isHighProtein: true, isHealthy: false },
  //   menus: [
  //     {
  //       menuId: "k22-m1",
  //       isPrimary: true,
  //       price: 9000,
  //       name: { ko: "순대국", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K23",
  //   name: "호우동 명지점",
  //   category: "한식",
  //   type: "식사",
  //   zone: "정문",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 324-21 1층",
  //   roadAddress: "서울특별시 서대문구 거북골로 29-3 1층",
  //   mapx: "1269246280",
  //   mapy: "375796903",
  //   lat: 37.5796904,
  //   lng: 126.924628,
  //   naverMapCode: 1020946950,
  //   minPrice: 6000,
  //   filters: { isCheap: true, isHighProtein: true, isHealthy: true },
  //   menus: [
  //     {
  //       menuId: "k23-m1",
  //       isPrimary: true,
  //       price: 6000,
  //       name: { ko: "우동", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k23-m2",
  //       isPrimary: true,
  //       price: 8000,
  //       name: { ko: "열무비빔밥", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k23-m3",
  //       isPrimary: true,
  //       price: 8000,
  //       name: { ko: "제육덮밥", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k23-m4",
  //       isPrimary: true,
  //       price: 9000,
  //       name: { ko: "돈까스", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k23-m5",
  //       isPrimary: false,
  //       name: { ko: "짜장면/밥", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K25",
  //   name: "돼지주막",
  //   category: "한식",
  //   type: "식사",
  //   zone: "정문",
  //   solo: false,
  //   address: "서울특별시 서대문구 남가좌동 324-17 지상1층",
  //   roadAddress: "서울특별시 서대문구 거북골로 25-6 지상1층",
  //   mapx: "1269247477",
  //   mapy: "375796739",
  //   lat: 37.5796833,
  //   lng: 126.9248052,
  //   naverMapCode: 1577370188,
  //   minPrice: 8000,
  //   filters: { isCheap: true, isHighProtein: true, isHealthy: false },
  //   menus: [
  //     {
  //       menuId: "k25-m1",
  //       isPrimary: true,
  //       price: 8000,
  //       name: { ko: "제육백반", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k25-m2",
  //       isPrimary: true,
  //       price: 8000,
  //       name: { ko: "삼겹백반", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K26",
  //   name: "명지 밥집",
  //   category: "한식",
  //   type: "식사",
  //   zone: "B",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 343-7 1층 명지밥집",
  //   roadAddress: "서울특별시 서대문구 거북골로 43-11 1층 명지밥집",
  //   mapx: "1269235975",
  //   mapy: "375790139",
  //   lat: 37.5790139,
  //   lng: 126.9235975,
  //   naverMapCode: 1106665543,
  //   minPrice: 11000,
  //   filters: { isCheap: false, isHighProtein: true, isHealthy: true },
  //   menus: [
  //     {
  //       menuId: "k26-m1",
  //       isPrimary: true,
  //       price: 11000,
  //       name: { ko: "김치찌개", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k26-m2",
  //       isPrimary: true,
  //       price: 11000,
  //       name: { ko: "제육덮밥", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k26-m3",
  //       isPrimary: true,
  //       price: 11000,
  //       name: { ko: "콩나물비빔밥", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k26-m4",
  //       isPrimary: true,
  //       price: 11000,
  //       name: { ko: "된장찌개", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k26-m5",
  //       isPrimary: true,
  //       price: 11000,
  //       name: { ko: "순두부찌개", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K27",
  //   name: "만득이네 두루치기",
  //   category: "한식",
  //   type: "식사",
  //   zone: "B",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 343-11",
  //   roadAddress: "서울특별시 서대문구 거북골로 43-12",
  //   mapx: "1269237181",
  //   mapy: "375789411",
  //   lat: 37.5789411,
  //   lng: 126.9237181,
  //   naverMapCode: 2007292156,
  //   minPrice: 10000,
  //   filters: { isCheap: false, isHighProtein: true, isHealthy: false },
  //   menus: [
  //     {
  //       menuId: "k27-m1",
  //       isPrimary: true,
  //       price: 10000,
  //       name: { ko: "두루치기", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k27-m2",
  //       isPrimary: true,
  //       price: 11000,
  //       name: { ko: "제육볶음", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k27-m3",
  //       isPrimary: true,
  //       price: 11000,
  //       name: { ko: "육개장", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k27-m4",
  //       isPrimary: true,
  //       price: 14000,
  //       name: { ko: "쭈꾸미철판", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k27-m5",
  //       isPrimary: true,
  //       price: 10000,
  //       name: { ko: "불고기", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K29",
  //   name: "킹콩부대찌개 명지대점",
  //   category: "한식",
  //   type: "식사",
  //   zone: "B",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 343-24 1층",
  //   roadAddress: "서울특별시 서대문구 증가로10길 23 1층",
  //   mapx: "1269235679",
  //   mapy: "375785213",
  //   lat: 37.5785213,
  //   lng: 126.9235679,
  //   naverMapCode: 1364845413,
  //   minPrice: 11000,
  //   filters: { isCheap: false, isHighProtein: true, isHealthy: false },
  //   menus: [
  //     {
  //       menuId: "k29-m1",
  //       isPrimary: true,
  //       price: 11000,
  //       name: { ko: "부대찌개", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K30",
  //   name: "군산식당",
  //   category: "한식",
  //   type: "식사",
  //   zone: "B",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 344-17",
  //   roadAddress: "서울특별시 서대문구 거북골로 53-18",
  //   mapx: "1269229896",
  //   mapy: "375781768",
  //   lat: 37.5781686,
  //   lng: 126.922898,
  //   naverMapCode: 21796089,
  //   minPrice: 6000,
  //   filters: { isCheap: true, isHighProtein: true, isHealthy: true },
  //   menus: [
  //     {
  //       menuId: "k30-m1",
  //       isPrimary: true,
  //       price: 6000,
  //       name: { ko: "가정식백반", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k30-m2",
  //       isPrimary: true,
  //       price: 6000,
  //       name: { ko: "된장/김치/참치찌개", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k30-m3",
  //       isPrimary: true,
  //       price: 7000,
  //       name: { ko: "제육볶음", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k30-m4",
  //       isPrimary: false,
  //       price: 6000,
  //       name: { ko: "청국장", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k30-m5",
  //       isPrimary: false,
  //       price: 6000,
  //       name: { ko: "순두부", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k30-m6",
  //       isPrimary: true,
  //       price: 9000,
  //       name: { ko: "생선조림", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K31",
  //   name: "고인돌식당",
  //   category: "한식",
  //   type: "식사",
  //   zone: "B",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 343-54",
  //   roadAddress: "서울특별시 서대문구 거북골로 53-9",
  //   mapx: "1269228083",
  //   mapy: "375783083",
  //   lat: 37.5783132,
  //   lng: 126.922829,
  //   naverMapCode: 18287122,
  //   minPrice: 6000,
  //   filters: { isCheap: true, isHighProtein: true, isHealthy: true },
  //   menus: [
  //     {
  //       menuId: "k31-m1",
  //       isPrimary: true,
  //       price: 7000,
  //       name: { ko: "덮밥류", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k31-m2",
  //       isPrimary: true,
  //       price: 6000,
  //       name: { ko: "볶음/비빔류", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k31-m3",
  //       isPrimary: true,
  //       price: 6000,
  //       name: { ko: "찌개류", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k31-m4",
  //       isPrimary: true,
  //       price: 6000,
  //       name: { ko: "국밥/탕류", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k31-m5",
  //       isPrimary: true,
  //       price: 7000,
  //       name: { ko: "국수/냉면", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k31-m6",
  //       isPrimary: false,
  //       price: 6000,
  //       name: { ko: "떡(만두)국", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K32",
  //   name: "일로칡냉면 명지대점",
  //   category: "한식",
  //   type: "식사",
  //   zone: "B",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 344-4",
  //   roadAddress: "서울특별시 서대문구 거북골로 53-4",
  //   mapx: "1269224745",
  //   mapy: "375782479",
  //   lat: 37.5781646,
  //   lng: 126.9223914,
  //   naverMapCode: 11700037,
  //   minPrice: 5000,
  //   filters: { isCheap: true, isHighProtein: false, isHealthy: false },
  //   menus: [
  //     {
  //       menuId: "k32-m1",
  //       isPrimary: true,
  //       price: 5000,
  //       name: { ko: "찐만두", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k32-m2",
  //       isPrimary: true,
  //       price: 6000,
  //       name: { ko: "칼국수", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k32-m3",
  //       isPrimary: true,
  //       price: 6000,
  //       name: { ko: "수제비", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K33",
  //   name: "밀이삭칼국수",
  //   category: "한식",
  //   type: "식사",
  //   zone: "B",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 350-7 1층",
  //   roadAddress: "서울특별시 서대문구 가재울로14길 29 1층",
  //   mapx: "1269216954",
  //   mapy: "375773498",
  //   lat: 37.5773498,
  //   lng: 126.9216954,
  //   naverMapCode: 1539314915,
  //   minPrice: 6000,
  //   filters: { isCheap: true, isHighProtein: false, isHealthy: true },
  //   menus: [
  //     {
  //       menuId: "k33-m1",
  //       isPrimary: true,
  //       price: 6000,
  //       name: { ko: "찐만두", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k33-m2",
  //       isPrimary: true,
  //       price: 7500,
  //       name: { ko: "야채비빔밥", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k33-m3",
  //       isPrimary: true,
  //       price: 8000,
  //       name: { ko: "수제비", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k33-m4",
  //       isPrimary: true,
  //       price: 8000,
  //       name: { ko: "칼국수", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K34",
  //   name: "미식가",
  //   category: "한식",
  //   type: "식사",
  //   zone: "B",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 347-22",
  //   roadAddress: "서울특별시 서대문구 가재울로10길 41",
  //   mapx: "1269227430",
  //   mapy: "375770355",
  //   lat: 37.5770705,
  //   lng: 126.92272,
  //   naverMapCode: 1643693487,
  //   minPrice: 9000,
  //   filters: { isCheap: false, isHighProtein: true, isHealthy: true },
  //   menus: [
  //     {
  //       menuId: "k34-m1",
  //       isPrimary: true,
  //       price: 10000,
  //       name: { ko: "돈까스", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k34-m2",
  //       isPrimary: true,
  //       price: 9500,
  //       name: { ko: "비빔밥", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k34-m3",
  //       isPrimary: false,
  //       price: 10000,
  //       name: { ko: "오징어덮밥", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k34-m4",
  //       isPrimary: true,
  //       price: 10000,
  //       name: { ko: "제육덮밥", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k34-m5",
  //       isPrimary: false,
  //       price: 10000,
  //       name: { ko: "불고기덮밥", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k34-m6",
  //       isPrimary: false,
  //       price: 9500,
  //       name: { ko: "순두부찌개", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k34-m7",
  //       isPrimary: false,
  //       price: 9000,
  //       name: { ko: "된장찌개", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K35",
  //   name: "백련팥죽",
  //   category: "한식",
  //   type: "식사",
  //   zone: "B",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 347-21",
  //   roadAddress: "서울특별시 서대문구 가재울로10길 39",
  //   mapx: "1269227346",
  //   mapy: "375769333",
  //   lat: 37.5769533,
  //   lng: 126.9227155,
  //   naverMapCode: 1715174013,
  //   minPrice: 10000,
  //   filters: { isCheap: true, isHighProtein: false, isHealthy: true },
  //   menus: [
  //     {
  //       menuId: "k35-m1",
  //       isPrimary: true,
  //       price: 7000,
  //       name: { ko: "보리밥", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k35-m2",
  //       isPrimary: true,
  //       price: 10000,
  //       name: { ko: "쌀팥죽", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k35-m3",
  //       isPrimary: true,
  //       price: 9000,
  //       name: { ko: "팥칼국수", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k35-m4",
  //       isPrimary: true,
  //       price: 10000,
  //       name: { ko: "새알팥죽", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K36",
  //   name: "통큰한식부페",
  //   category: "한식",
  //   type: "식사",
  //   zone: "B",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 345-2 2층",
  //   roadAddress: "서울특별시 서대문구 증가로 131 (남가좌동) 2층",
  //   mapx: "1269230275",
  //   mapy: "375772798",
  //   lat: 37.5772798,
  //   lng: 126.9230275,
  //   naverMapCode: 1438663093,
  //   minPrice: 8000,
  //   filters: { isCheap: true, isHighProtein: true, isHealthy: true },
  //   menus: [
  //     {
  //       menuId: "k36-m1",
  //       isPrimary: true,
  //       price: 8000,
  //       name: { ko: "한식뷔페", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K37",
  //   name: "기쁨이네",
  //   category: "한식",
  //   type: "식사",
  //   zone: "B",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 345-4",
  //   roadAddress: "서울특별시 서대문구 가재울로6길 53-87",
  //   mapx: "1269231168",
  //   mapy: "375770219",
  //   lat: 37.5770219,
  //   lng: 126.9231168,
  //   naverMapCode: 1526953217,
  //   minPrice: 4000,
  //   filters: { isCheap: true, isHighProtein: true, isHealthy: false },
  //   menus: [
  //     {
  //       menuId: "k37-m1",
  //       isPrimary: true,
  //       price: 4000,
  //       name: { ko: "라면", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k37-m2",
  //       isPrimary: true,
  //       price: 6000,
  //       name: { ko: "비빔국수", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k37-m3",
  //       isPrimary: true,
  //       price: 9000,
  //       name: { ko: "순대국", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k37-m4",
  //       isPrimary: true,
  //       price: 10000,
  //       name: { ko: "육개장", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k37-m5",
  //       isPrimary: true,
  //       price: 6000,
  //       name: { ko: "족발", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K38",
  //   name: "기린식당",
  //   category: "한식",
  //   type: "식사",
  //   zone: "B",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 345-4",
  //   roadAddress: "서울특별시 서대문구 가재울로6길 53-87",
  //   mapx: "1269229465",
  //   mapy: "375769230",
  //   lat: 37.5770219,
  //   lng: 126.9231168,
  //   naverMapCode: 1601474310,
  //   minPrice: null,
  //   filters: { isCheap: false, isHighProtein: true, isHealthy: true },
  //   menus: [
  //     {
  //       menuId: "k38-m1",
  //       isPrimary: true,
  //       name: { ko: "찌개류", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k38-m2",
  //       isPrimary: true,
  //       name: { ko: "덮밥류", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k38-m3",
  //       isPrimary: true,
  //       name: { ko: "국수류", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k38-m4",
  //       isPrimary: true,
  //       name: { ko: "비빔밥", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k38-m5",
  //       isPrimary: true,
  //       name: { ko: "내장/갈비탕", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k38-m5",
  //       isPrimary: true,
  //       name: { ko: "육개장", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K40",
  //   name: "정가네맛집",
  //   category: "한식",
  //   type: "식사",
  //   zone: "B",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 344-40",
  //   roadAddress: "서울특별시 서대문구 증가로10길 3",
  //   mapx: "1269230764",
  //   mapy: "375777197",
  //   lat: 37.5777197,
  //   lng: 126.9230764,
  //   naverMapCode: 1303536115,
  //   minPrice: 9000,
  //   filters: { isCheap: false, isHighProtein: true, isHealthy: true },
  //   menus: [
  //     {
  //       menuId: "k40-m1",
  //       isPrimary: true,
  //       price: 9000,
  //       name: { ko: "생선구이류", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k40-m2",
  //       isPrimary: true,
  //       price: 9000,
  //       name: { ko: "된장찌개", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k40-m3",
  //       isPrimary: true,
  //       price: 9000,
  //       name: { ko: "순두부찌개", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k40-m4",
  //       isPrimary: true,
  //       price: 10000,
  //       name: { ko: "청국장찌개", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k40-m5",
  //       isPrimary: true,
  //       price: 10000,
  //       name: { ko: "황태해장국", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K41",
  //   name: "본죽&비빔밥 남가좌점",
  //   category: "한식",
  //   type: "식사",
  //   zone: "B",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 340-32 백련빌딩 1층 106호",
  //   roadAddress: "서울특별시 서대문구 증가로 122 남가좌동 백련빌딩 1층 106호",
  //   mapx: "1269243486",
  //   mapy: "375773237",
  //   lat: 37.5773796,
  //   lng: 126.9242848,
  //   naverMapCode: 6000,
  //   minPrice: 10000,
  //   filters: { isCheap: false, isHighProtein: false, isHealthy: true },
  //   menus: [
  //     {
  //       menuId: "k41-m1",
  //       isPrimary: true,
  //       price: 6000,
  //       name: { ko: "흰죽", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k41-m2",
  //       isPrimary: true,
  //       price: 10000,
  //       name: { ko: "야채죽", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k41-m3",
  //       isPrimary: true,
  //       price: 13000,
  //       name: { ko: "전복죽", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k41-m4",
  //       isPrimary: true,
  //       price: 13000,
  //       name: { ko: "불고기낙지비빔밥", en: "", zh: "", ja: "" },
  //     },
  //     {
  //       menuId: "k41-m5",
  //       isPrimary: true,
  //       price: 12000,
  //       name: { ko: "장조림버터비빔밥", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
  // {
  //   id: "K43",
  //   name: "정주보쌈",
  //   category: "한식",
  //   type: "식사",
  //   zone: "B",
  //   solo: true,
  //   address: "서울특별시 서대문구 남가좌동 338-41 정주보쌈",
  //   roadAddress: "서울특별시 서대문구 가재울로4길 63 정주보쌈",
  //   mapx: "1269247014",
  //   mapy: "375764466",
  //   lat: 37.5764578,
  //   lng: 126.9246604,
  //   naverMapCode: 1760908956,
  //   minPrice: null,
  //   filters: { isCheap: false, isHighProtein: true, isHealthy: false },
  //   menus: [
  //     {
  //       menuId: "k43-m1",
  //       isPrimary: true,
  //       name: { ko: "보쌈", en: "", zh: "", ja: "" },
  //     },
  //   ],
  // },
];

//   //// 15일은 여기까지. ///
//   //// 15일은 여기까지. ///
//   //// 15일은 여기까지. ///
//   //// 15일은 여기까지. ///
//   //// 15일은 여기까지. ///
//   //// 15일은 여기까지. ///
//   //// 15일은 여기까지. ///
//   //// 15일은 여기까지. ///
//   //// 15일은 여기까지. ///
//   //// 15일은 여기까지. ///
//   //// 15일은 여기까지. ///
//   //// 15일은 여기까지. ///
//   //// 15일은 여기까지. ///
//   //// 15일은 여기까지. ///
//   //// 15일은 여기까지. ///
//   //// 15일은 여기까지. ///
//   //// 15일은 여기까지. ///

//   {
//     id: "J1",
//     name: "라라유부 명지대 본점",
//     category: "일식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 401-16 1층",
//     roadAddress: "서울특별시 서대문구 거북골로 14 1층",
//     mapx: "1269256375",
//     mapy: "375808250",
//     lat: 37.5808695,
//     lng: 126.9255787,
//   },
//   {
//     id: "J2",
//     name: "활구팔구",
//     category: "일식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 401-46 . 1층() 활구팔구",
//     roadAddress: "서울특별시 서대문구 거북골로 18 . 1층(홍은동) 활구팔구",
//     mapx: "1269253255",
//     mapy: "375806124",
//     lat: 37.5806209,
//     lng: 126.9253011,
//   },
//   {
//     id: "J3",
//     name: "3KG이상대광어횟집",
//     category: "일식",
//     type: "식사",
//     zone: "C",
//     solo: false,
//     address: "서울특별시 서대문구 홍은동 401-25 1층",
//     roadAddress: "서울특별시 서대문구 거북골로 12-15 1층",
//     mapx: "1269254474",
//     mapy: "375809236",
//     lat: 37.5809718,
//     lng: 126.9254713,
//   },
//   {
//     id: "J4",
//     name: "왕포수산",
//     category: "일식",
//     type: "식사",
//     zone: "C",
//     solo: false,
//     address: "서울특별시 서대문구 홍은동 400-37 1,2층",
//     roadAddress: "서울특별시 서대문구 거북골로 8 1,2층",
//     mapx: "1269261622",
//     mapy: "375811823",
//     lat: 37.5812322,
//     lng: 126.9261394,
//   },
//   {
//     id: "J5",
//     name: "긴자료코 명지대점",
//     category: "일식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 401-1 1층 긴자료코",
//     roadAddress: "서울특별시 서대문구 명지대2길 14 1층 긴자료코",
//     mapx: "1269252155",
//     mapy: "375818578",
//     lat: 37.5818267,
//     lng: 126.9252269,
//   },
//   {
//     id: "J6",
//     name: "스시하나에",
//     category: "일식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 421-14 2층",
//     roadAddress: "서울특별시 서대문구 명지대길 24 2층",
//     mapx: "1269249100",
//     mapy: "375814958",
//     lat: 37.5814699,
//     lng: 126.9248963,
//   },
//   {
//     id: "J7",
//     name: "타코야끼 오늘",
//     category: "일식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 421-24 1층",
//     roadAddress: "서울특별시 서대문구 명지대길 40 1층",
//     mapx: "1269243559",
//     mapy: "375820193",
//     lat: 37.5820462,
//     lng: 126.9243371,
//   },
//   {
//     id: "J8",
//     name: "여부초밥 명지대점",
//     category: "일식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 421-24 1층",
//     roadAddress: "서울특별시 서대문구 명지대길 40 1층",
//     mapx: "1269243371",
//     mapy: "375820462",
//     lat: 37.5820162,
//     lng: 126.9243271,
//   },
//   {
//     id: "J9",
//     name: "가타쯔무리",
//     category: "일식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 8-25",
//     roadAddress: "서울특별시 서대문구 명지대길 72",
//     mapx: "1269234861",
//     mapy: "375832536",
//     lat: 37.583234,
//     lng: 126.9234446,
//   },
//   {
//     id: "J10",
//     name: "소소식탁 명지대",
//     category: "일식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 3-77 1층",
//     roadAddress: "서울특별시 서대문구 명지대길 75 1층",
//     mapx: "1269231367",
//     mapy: "375833401",
//     lat: 37.5833273,
//     lng: 126.9231588,
//   },
//   {
//     id: "J11",
//     name: "만평우동 명지대점",
//     category: "일식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 3-2 1층 106호",
//     roadAddress: "서울특별시 서대문구 명지대길 83 1층 106호",
//     mapx: "1269231109",
//     mapy: "375837930",
//     lat: 37.583659,
//     lng: 126.9230508,
//   },
//   {
//     id: "J12",
//     name: "핵밥 명지대점",
//     category: "일식",
//     type: "식사",
//     zone: "정문",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 324-19 2층",
//     roadAddress: "서울특별시 서대문구 거북골로 25-1 2층",
//     mapx: "1269246131",
//     mapy: "375798713",
//     lat: 37.5798572,
//     lng: 126.9246214,
//   },
//   {
//     id: "J13",
//     name: "육초연 명지대점",
//     category: "일식",
//     type: "식사",
//     zone: "정문",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 324-8 1층",
//     roadAddress: "서울특별시 서대문구 거북골로 21-12 1층",
//     mapx: "1269250879",
//     mapy: "375797257",
//     lat: 37.5797158,
//     lng: 126.9250571,
//   },
//   {
//     id: "J14",
//     name: "화전",
//     category: "일식",
//     type: "식사",
//     zone: "정문",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 324-42",
//     roadAddress: "서울특별시 서대문구 거북골로 33-4",
//     mapx: "1269240574",
//     mapy: "375792657",
//     lat: 37.5792567,
//     lng: 126.9239779,
//   },
//   {
//     id: "J15",
//     name: "김은수참치",
//     category: "일식",
//     type: "식사",
//     zone: "정문",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 324-45 2층",
//     roadAddress: "서울특별시 서대문구 증가로10길 41 2층",
//     mapx: "1269242862",
//     mapy: "375790294",
//     lat: 37.5790294,
//     lng: 126.9242862,
//   },
//   {
//     id: "J16",
//     name: "나라비",
//     category: "일식",
//     type: "식사",
//     zone: "B",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 343-1",
//     roadAddress: "서울특별시 서대문구 거북골로 39",
//     mapx: "1269235892",
//     mapy: "375791494",
//     lat: 37.5791494,
//     lng: 126.9235892,
//   },
//   {
//     id: "J17",
//     name: "아쯔다무라",
//     category: "일식",
//     type: "식사",
//     zone: "B",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 343-14",
//     roadAddress: "서울특별시 서대문구 증가로10길 25",
//     mapx: "1269236424",
//     mapy: "375786246",
//     lat: 37.5786694,
//     lng: 126.9235987,
//   },
//   {
//     id: "J18",
//     name: "나베야 남가좌명지대점",
//     category: "일식",
//     type: "식사",
//     zone: "B",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 388 상가동 B307호",
//     roadAddress: "서울특별시 서대문구 증가로 150 상가동 B307호",
//     mapx: "1269218119",
//     mapy: "375782188",
//     lat: 37.5783341,
//     lng: 126.921898,
//   },
//   {
//     id: "J19",
//     name: "신 부산스시",
//     category: "일식",
//     type: "식사",
//     zone: "B",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 347-13 1층",
//     roadAddress: "서울특별시 서대문구 가재울로12길 40 1층",
//     mapx: "1269224103",
//     mapy: "375772302",
//     lat: 37.5772302,
//     lng: 126.9224103,
//   },
//   {
//     id: "J20",
//     name: "육회바른연어 명지대점",
//     category: "일식",
//     type: "식사",
//     zone: "B",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 339-29 육회바른연어 1층",
//     roadAddress: "서울특별시 서대문구 증가로 110 육회바른연어 1층",
//     mapx: "1269252828",
//     mapy: "375767301",
//     lat: 37.5767342,
//     lng: 126.9253428,
//   },
//   {
//     id: "C1",
//     name: "왕가주방",
//     category: "중식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 401-40 1층 101호",
//     roadAddress: "서울특별시 서대문구 거북골로 10 1층 101호",
//     mapx: "1269260002",
//     mapy: "375810863",
//     lat: 37.5810706,
//     lng: 126.9258533,
//   },
//   {
//     id: "C2",
//     name: "춘리마라탕 명지대점",
//     category: "중식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 401-40",
//     roadAddress: "서울특별시 서대문구 거북골로 10",
//     mapx: "1269258840",
//     mapy: "375809928",
//     lat: 37.5810706,
//     lng: 126.9259133,
//   },
//   {
//     id: "C3",
//     name: "마라왕마라탕",
//     category: "중식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 401-16 1층 마라왕마라탕",
//     roadAddress: "서울특별시 서대문구 거북골로 14 1층 마라왕마라탕",
//     mapx: "1269256755",
//     mapy: "375808682",
//     lat: 37.5808295,
//     lng: 126.9255787,
//   },
//   {
//     id: "C4",
//     name: "라와마라탕 명지대점",
//     category: "중식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 401-15",
//     roadAddress: "서울특별시 서대문구 명지대길 10",
//     mapx: "1269251102",
//     mapy: "375807558",
//     lat: 37.58081,
//     lng: 126.9251407,
//   },
//   {
//     id: "C5",
//     name: "미르중식",
//     category: "중식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 401-13 1층",
//     roadAddress: "서울특별시 서대문구 명지대길 18 1층",
//     mapx: "1269250383",
//     mapy: "375811844",
//     lat: 37.5812264,
//     lng: 126.925081,
//   },
//   {
//     id: "C6",
//     name: "탕화쿵푸마라탕 명지대점",
//     category: "중식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 421-28",
//     roadAddress: "서울특별시 서대문구 명지대길 38",
//     mapx: "1269244898",
//     mapy: "375819465",
//     lat: 37.5819549,
//     lng: 126.9245051,
//   },
//   {
//     id: "C7",
//     name: "유진반점",
//     category: "중식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 은평구 갈현동 505-22",
//     roadAddress: "서울특별시 은평구 갈현로 219",
//     mapx: "1269236537",
//     mapy: "375820863",
//     lat: 37.6167788,
//     lng: 126.9144398,
//   },
//   {
//     id: "C8",
//     name: "진짜루",
//     category: "중식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 3-111",
//     roadAddress: "서울특별시 서대문구 명지대길 73",
//     mapx: "1269231840",
//     mapy: "375832491",
//     lat: 37.5832491,
//     lng: 126.9231723,
//   },
//   {
//     id: "C9",
//     name: "다복향마라탕 명지대점",
//     category: "중식",
//     type: "식사",
//     zone: "A",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 409-34 1층",
//     roadAddress: "서울특별시 서대문구 거북골로 17 1층",
//     mapx: "1269254036",
//     mapy: "375804343",
//     lat: 37.5804202,
//     lng: 126.9254372,
//   },
//   {
//     id: "C10",
//     name: "성연마라탕",
//     category: "중식",
//     type: "식사",
//     zone: "A",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 409-47 2층",
//     roadAddress: "서울특별시 서대문구 거북골로 19-1 2층",
//     mapx: "1269251904",
//     mapy: "375802465",
//     lat: 37.5802892,
//     lng: 126.9251834,
//   },
//   {
//     id: "C11",
//     name: "샹츠마라 명지대점",
//     category: "중식",
//     type: "식사",
//     zone: "정문",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 324-24 1층 샹츠마라 명지대점",
//     roadAddress: "서울특별시 서대문구 거북골로 29 1층 샹츠마라 명지대점",
//     mapx: "1269243927",
//     mapy: "375797283",
//     lat: 37.5797056,
//     lng: 126.9244004,
//   },
//   {
//     id: "C12",
//     name: "짜우반점",
//     category: "중식",
//     type: "식사",
//     zone: "정문",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 324-25",
//     roadAddress: "서울특별시 서대문구 거북골로 29-4",
//     mapx: "1269245080",
//     mapy: "375796138",
//     lat: 37.5796076,
//     lng: 126.9245087,
//   },
//   {
//     id: "C13",
//     name: "완푸",
//     category: "중식",
//     type: "식사",
//     zone: "정문",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 325-16 1층",
//     roadAddress: "서울특별시 서대문구 증가로10길 36-3 1층",
//     mapx: "1269243617",
//     mapy: "375787490",
//     lat: 37.5787564,
//     lng: 126.9243617,
//   },
//   {
//     id: "C14",
//     name: "궁가",
//     category: "중식",
//     type: "식사",
//     zone: "정문",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 325-1",
//     roadAddress: "서울특별시 서대문구 증가로10길 60-4",
//     mapx: "1269252096",
//     mapy: "375793676",
//     lat: 37.5793843,
//     lng: 126.925162,
//   },
//   {
//     id: "C15",
//     name: "중화루",
//     category: "중식",
//     type: "식사",
//     zone: "정문",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 326-12",
//     roadAddress: "서울특별시 서대문구 증가로8길 24-1",
//     mapx: "1269249625",
//     mapy: "375781447",
//     lat: 37.5781515,
//     lng: 126.9249893,
//   },
//   {
//     id: "C16",
//     name: "세아짬뽕",
//     category: "중식",
//     type: "식사",
//     zone: "B",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 343-17 1층 세아빰뽕",
//     roadAddress: "서울특별시 서대문구 거북골로 37-10 1층 세아빰뽕",
//     mapx: "1269239156",
//     mapy: "375789704",
//     lat: 37.5789286,
//     lng: 126.9239128,
//   },
//   {
//     id: "C17",
//     name: "성연양꼬치",
//     category: "중식",
//     type: "식사",
//     zone: "B",
//     solo: false,
//     address: "서울특별시 서대문구 남가좌동 343-30",
//     roadAddress: "서울특별시 서대문구 거북골로 53-11",
//     mapx: "1269229943",
//     mapy: "375782690",
//     lat: 37.5782924,
//     lng: 126.9230026,
//   },
//   {
//     id: "C18",
//     name: "미향만두전문점",
//     category: "중식",
//     type: "식사",
//     zone: "B",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 344-6 1층",
//     roadAddress: "서울특별시 서대문구 거북골로 57 1층",
//     mapx: "1269221003",
//     mapy: "375781456",
//     lat: 37.5781189,
//     lng: 126.9221024,
//   },
//   {
//     id: "C19",
//     name: "차푸 본점",
//     category: "중식",
//     type: "식사",
//     zone: "B",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 345-4",
//     roadAddress: "서울특별시 서대문구 남가좌동 가재울로6길 53-87",
//     mapx: "1269230510",
//     mapy: "375769412",
//     lat: 37.576919,
//     lng: 126.923083,
//   },
//   {
//     id: "W1",
//     name: "빨간토마토피자본점",
//     category: "양식·아시안",
//     type: "식사",
//     zone: "C",
//     solo: false,
//     address: "서울특별시 서대문구 홍은동 400-40 1층 빨간토마토피자",
//     roadAddress: "서울특별시 서대문구 거북골로 8-10 1층 빨간토마토피자",
//     mapx: "1269259155",
//     mapy: "375814683",
//     lat: 37.5814836,
//     lng: 126.9259124,
//   },
//   {
//     id: "W2",
//     name: "리코",
//     category: "양식·아시안",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 401-18 2층",
//     roadAddress: "서울특별시 서대문구 거북골로 20 2층",
//     mapx: "1269251596",
//     mapy: "375805419",
//     lat: 37.5805419,
//     lng: 126.9251596,
//   },
//   {
//     id: "W3",
//     name: "피자스쿨 명지대점",
//     category: "양식·아시안",
//     type: "식사",
//     zone: "C",
//     solo: false,
//     address: "서울특별시 서대문구 홍은동 401-16 1층",
//     roadAddress: "서울특별시 서대문구 거북골로 14 1층",
//     mapx: "1269255704",
//     mapy: "375807955",
//     lat: 37.5807695,
//     lng: 126.9255187,
//   },
//   {
//     id: "W4",
//     name: "베트남쌀국수포녹",
//     category: "양식·아시안",
//     type: "식사",
//     zone: "A",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 409-48",
//     roadAddress: "서울특별시 서대문구 거북골로 21-7",
//     mapx: "1269252468",
//     mapy: "375799471",
//     lat: 37.5799472,
//     lng: 126.9252468,
//   },
//   {
//     id: "W5",
//     name: "명지샤브",
//     category: "양식·아시안",
//     type: "식사",
//     zone: "A",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 409-51",
//     roadAddress: "서울특별시 서대문구 증가로10길 63",
//     mapx: "1269253047",
//     mapy: "375797125",
//     lat: 37.5796935,
//     lng: 126.9252971,
//   },
//   {
//     id: "W6",
//     name: "꾸오레 베로",
//     category: "양식·아시안",
//     type: "식사",
//     zone: "A",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 410-50",
//     roadAddress: "서울특별시 서대문구 증가로10길 60-9",
//     mapx: "1269255427",
//     mapy: "375791759",
//     lat: 37.5791848,
//     lng: 126.9255659,
//   },
//   {
//     id: "W7",
//     name: "피나치공 서대문홍은점",
//     category: "양식·아시안",
//     type: "식사",
//     zone: "A",
//     solo: false,
//     address: "서울특별시 서대문구 홍은동 409-25 1층",
//     roadAddress: "서울특별시 서대문구 증가로10길 77 1층",
//     mapx: "1269259151",
//     mapy: "375801057",
//     lat: 37.5801057,
//     lng: 126.9259225,
//   },
//   {
//     id: "W8",
//     name: "주인백 파스타",
//     category: "양식·아시안",
//     type: "식사",
//     zone: "정문",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 324-11",
//     roadAddress: "서울특별시 서대문구 증가로10길 57",
//     mapx: "1269249226",
//     mapy: "375795267",
//     lat: 37.5795268,
//     lng: 126.9249226,
//   },
//   {
//     id: "W9",
//     name: "타코볼볼 명지대점",
//     category: "양식·아시안",
//     type: "식사",
//     zone: "정문",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 324-20 2층",
//     roadAddress: "서울특별시 서대문구 거북골로 27 2층",
//     mapx: "1269245223",
//     mapy: "375797852",
//     lat: 37.5797852,
//     lng: 126.9245223,
//   },
//   {
//     id: "W10",
//     name: "밀",
//     category: "양식·아시안",
//     type: "식사",
//     zone: "B",
//     solo: false,
//     address: "서울특별시 서대문구 남가좌동 340-25 1층",
//     roadAddress: "서울특별시 서대문구 증가로8길 8-1 1층",
//     mapx: "1269243184",
//     mapy: "375777105",
//     lat: 37.5777285,
//     lng: 126.9243531,
//   },
//   {
//     id: "W11",
//     name: "미분당 가좌점",
//     category: "양식·아시안",
//     type: "식사",
//     zone: "B",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 340-32 백련빌딩 1층",
//     roadAddress: "서울특별시 서대문구 증가로 122 백련빌딩 1층",
//     mapx: "1269241968",
//     mapy: "375773645",
//     lat: 37.5773796,
//     lng: 126.9242848,
//   },
//   {
//     id: "W12",
//     name: "라온아토",
//     category: "양식·아시안",
//     type: "식사",
//     zone: "B",
//     solo: false,
//     address: "서울특별시 서대문구 남가좌동 339-8 1층",
//     roadAddress: "서울특별시 서대문구 증가로4길 13 1층",
//     mapx: "1269259739",
//     mapy: "375768867",
//     lat: 37.5769127,
//     lng: 126.9259801,
//   },
//   {
//     id: "F1",
//     name: "본도시락 명지대점",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 401-28 1층",
//     roadAddress: "서울특별시 서대문구 거북골로 16 1층",
//     mapx: "1269254081",
//     mapy: "375806619",
//     lat: 37.5807155,
//     lng: 126.9253988,
//   },
//   {
//     id: "F2",
//     name: "김밥천국 명지점",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 401-18 1층",
//     roadAddress: "서울특별시 서대문구 거북골로 20 1층",
//     mapx: "1269251354",
//     mapy: "375804965",
//     lat: 37.5805719,
//     lng: 126.9251896,
//   },
//   {
//     id: "F3",
//     name: "허니돈 명지대점",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 401-4 1층",
//     roadAddress: "서울특별시 서대문구 명지대2길 8 1층",
//     mapx: "1269251491",
//     mapy: "375816454",
//     lat: 37.5816004,
//     lng: 126.9251705,
//   },
//   {
//     id: "F4",
//     name: "리코브리또",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 322-16 1층",
//     roadAddress: "서울특별시 서대문구 명지대1길 6 1층",
//     mapx: "1269245726",
//     mapy: "375812848",
//     lat: 37.5813003,
//     lng: 126.924537,
//   },
//   {
//     id: "F5",
//     name: "응급실떡볶이 남가좌점",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 322-8",
//     roadAddress: "서울특별시 서대문구 명지대길 41",
//     mapx: "1269241229",
//     mapy: "375819980",
//     lat: 37.5820049,
//     lng: 126.9240986,
//   },
//   {
//     id: "F6",
//     name: "미소떡볶이",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 5-178",
//     roadAddress: "서울특별시 서대문구 명지대3길 1",
//     mapx: "1269236825",
//     mapy: "375822067",
//     lat: 37.5822101,
//     lng: 126.9236475,
//   },
//   {
//     id: "F7",
//     name: "행복한떡볶이",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "C",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 341-5",
//     roadAddress: "서울특별시 서대문구 가좌로 145",
//     mapx: "1269233627",
//     mapy: "375848613",
//     lat: 37.5848696,
//     lng: 126.923321,
//   },
//   {
//     id: "F8",
//     name: "얌얌샐러드",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "A",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 409-58 1층",
//     roadAddress: "서울특별시 서대문구 거북골로 11 1층",
//     mapx: "1269259968",
//     mapy: "375808279",
//     lat: 37.5808011,
//     lng: 126.9259773,
//   },
//   {
//     id: "F9",
//     name: "순이네고릴라떡볶이본점",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "A",
//     solo: true,
//     address: "서울특별시 서대문구 홍은동 409-33",
//     roadAddress: "서울특별시 서대문구 거북골로 15-2",
//     mapx: "1269255478",
//     mapy: "375804952",
//     lat: 37.5804952,
//     lng: 126.9255478,
//   },
//   {
//     id: "F10",
//     name: "써브웨이 명지대점",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "정문",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 324-2",
//     roadAddress: "서울특별시 서대문구 거북골로 23",
//     mapx: "1269248582",
//     mapy: "375800709",
//     lat: 37.5800142,
//     lng: 126.9248636,
//   },
//   {
//     id: "F11",
//     name: "맥도날드 명지대점",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "정문",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 324-3",
//     roadAddress: "서울특별시 서대문구 남가좌동 거북골로 25",
//     mapx: "1269247604",
//     mapy: "375799373",
//     lat: 37.57991,
//     lng: 126.924747,
//   },
//   {
//     id: "F12",
//     name: "한솥도시락 명지대앞점",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "정문",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 324-20 1층",
//     roadAddress: "서울특별시 서대문구 거북골로 27 1층",
//     mapx: "1269244957",
//     mapy: "375798099",
//     lat: 37.5798252,
//     lng: 126.9244923,
//   },
//   {
//     id: "F13",
//     name: "슬로우캘리 명지대점",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "정문",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 324-24 1층",
//     roadAddress: "서울특별시 서대문구 거북골로 29 1층",
//     mapx: "1269243489",
//     mapy: "375797085",
//     lat: 37.5797256,
//     lng: 126.9243304,
//   },
//   {
//     id: "F14",
//     name: "롯데리아 명지대학점",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "정문",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 324-31",
//     roadAddress: "서울특별시 서대문구 거북골로 31",
//     mapx: "1269242960",
//     mapy: "375796240",
//     lat: 37.5795779,
//     lng: 126.9243472,
//   },
//   {
//     id: "F15",
//     name: "동대문엽기떡볶이 명지대점",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "정문",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 324-35 2층",
//     roadAddress: "서울특별시 서대문구 거북골로 33 2층",
//     mapx: "1269240813",
//     mapy: "375794650",
//     lat: 37.579465,
//     lng: 126.9240813,
//   },
//   {
//     id: "F16",
//     name: "신전떡볶이 명지대점",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "정문",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 324-48 1층",
//     roadAddress: "서울특별시 서대문구 거북골로 37-7 1층",
//     mapx: "1269239529",
//     mapy: "375790871",
//     lat: 37.5790959,
//     lng: 126.9240002,
//   },
//   {
//     id: "F17",
//     name: "엄마손떡볶이",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "정문",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 324-46",
//     roadAddress: "서울특별시 서대문구 증가로10길 37",
//     mapx: "1269241615",
//     mapy: "375789339",
//     lat: 37.5789392,
//     lng: 126.9241625,
//   },
//   {
//     id: "F18",
//     name: "더김밥 명지대점",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "정문",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 324-38 1층 더 김밥",
//     roadAddress: "서울특별시 서대문구 증가로10길 47 1층 더 김밥",
//     mapx: "1269245640",
//     mapy: "375792260",
//     lat: 37.579226,
//     lng: 126.924564,
//   },
//   {
//     id: "F19",
//     name: "이삭토스트 명지대점",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "B",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 343-1",
//     roadAddress: "서울특별시 서대문구 거북골로 39",
//     mapx: "1269235188",
//     mapy: "375791337",
//     lat: 37.5791494,
//     lng: 126.9235892,
//   },
//   {
//     id: "F20",
//     name: "맘스터치 명지대점",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "B",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 343-3 1-2층",
//     roadAddress: "서울특별시 서대문구 거북골로 41 1-2층",
//     mapx: "1269234114",
//     mapy: "375790415",
//     lat: 37.5790416,
//     lng: 126.9234114,
//   },
//   {
//     id: "F21",
//     name: "만두성지",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "B",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 343-43 1층 103호",
//     roadAddress: "서울특별시 서대문구 거북골로 47 1층 103호",
//     mapx: "1269229185",
//     mapy: "375786946",
//     lat: 37.5787009,
//     lng: 126.9229319,
//   },
//   {
//     id: "F22",
//     name: "스텔라떡볶이 서울명지대점",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "B",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 388 DMC아이파크 상가 B309호",
//     roadAddress: "서울특별시 서대문구 증가로 150 DMC아이파크 상가 B309호",
//     mapx: "1269219763",
//     mapy: "375783330",
//     lat: 37.5781841,
//     lng: 126.921598,
//   },
//   {
//     id: "F23",
//     name: "어글리김밥",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "B",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 388 상가동 B305호",
//     roadAddress: "서울특별시 서대문구 증가로 150 상가동 B305호",
//     mapx: "1269215756",
//     mapy: "375780832",
//     lat: 37.5778841,
//     lng: 126.921298,
//   },
//   {
//     id: "F24",
//     name: "호시타코야끼 명지대점",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "B",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 344-33 1층",
//     roadAddress: "서울특별시 서대문구 증가로 140 1층",
//     mapx: "1269220283",
//     mapy: "375777203",
//     lat: 37.5777403,
//     lng: 126.9220356,
//   },
//   {
//     id: "F25",
//     name: "왕만두 쉐프 명지대점",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "B",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 347-1 1층",
//     roadAddress: "서울특별시 서대문구 증가로 135 1층",
//     mapx: "1269223913",
//     mapy: "375774041",
//     lat: 37.5773747,
//     lng: 126.9224381,
//   },
//   {
//     id: "F26",
//     name: "하나네김밥",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "B",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 347-1 1층",
//     roadAddress: "서울특별시 서대문구 증가로 135 1층",
//     mapx: "1269224692",
//     mapy: "375773904",
//     lat: 37.5773747,
//     lng: 126.9224381,
//   },
//   {
//     id: "F27",
//     name: "이정희떡볶이",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "B",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 341-1",
//     roadAddress: "서울특별시 서대문구 증가로10길 14",
//     mapx: "1269233090",
//     mapy: "375780830",
//     lat: 37.5780911,
//     lng: 126.9233338,
//   },
//   {
//     id: "F28",
//     name: "담꾹 남가좌점",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "B",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 345-3 1층",
//     roadAddress: "서울특별시 서대문구 증가로 129 1층",
//     mapx: "1269232174",
//     mapy: "375773158",
//     lat: 37.5772818,
//     lng: 126.9232676,
//   },
//   {
//     id: "F29",
//     name: "호호키친",
//     category: "간편식·분식",
//     type: "식사",
//     zone: "B",
//     solo: true,
//     address: "서울특별시 서대문구 남가좌동 338-58 1층",
//     roadAddress: "서울특별시 서대문구 가재울로6길 53-36 1층",
//     mapx: "1269235190",
//     mapy: "375767918",
//     lat: 37.57682,
//     lng: 126.9235519,
//   },
// ];
